"""Feinschliff · Graphical — horizontal bar chart for category breakdowns.

Reference: brands/feinschliff/claude-design/feinschliff-2026.html `<section data-label="Graphical">`.

Composition:
  - Standard content header (eyebrow + title) painted by `content_header`.
  - 4 horizontal bar rows in the content area (schema allows 3–6; the
    template renders 4 sample rows — extra rows can be added at slide-edit
    time by filling placeholders that exist for up to 6 bars).
  - Per-bar: left-aligned mono label, a coloured bar whose width is
    proportional to `value` (0–100 percent), and a right-aligned mono
    value text. Accent bars fill in T.ACCENT; plain bars fill in T.INK.
  - Thin T.FOG hairline below every row.
  - Mono source caption at the bottom.

Placeholder map (idx → field):
    0          title
    10         eyebrow
    20 + i*4   bars[i].label    (i = 0..5)
    21 + i*4   bars[i].value    (i = 0..5)
    60         source

Only label + value are placeholders per bar; the `accent` boolean is not
editable at slide-edit time (it's baked into the layout per-row so users
don't accidentally repaint the entire chart orange). Users who need to
re-accent a different row can re-run /deck with the updated bars list.
"""
from __future__ import annotations

import theme as T
from components import (
    add_rect, add_text_placeholder, paint_chrome,
    set_layout_background, set_layout_name,
)
from components.graphical_bars import add_graphical_bars
from layouts._shared import content_header


NAME = 'Feinschliff · Graphical'
BG = 'white'
PGMETA = 'Graphical'
EYEBROW_PROMPT = 'Share of revenue by region'
TITLE_PROMPT = 'EMEA still leads; NAM closing the gap.'

# Schema preserved verbatim from the stub (auto-generated by compile.py).
# compile.py reads this when syncing the catalog, so any edit here must
# be mirrored in brands/feinschliff/catalog/layouts.json.
SLOTS_SCHEMA = {
    "eyebrow": {
        "type": "string",
        "maxLength": 60,
        "optional": True
    },
    "title": {
        "type": "string",
        "maxLength": 80
    },
    "bars": {
        "type": "array",
        "minItems": 3,
        "maxItems": 6,
        "items": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string",
                    "maxLength": 20
                },
                "value": {
                    "type": "number",
                    "description": "Percent, 0–100."
                },
                "accent": {
                    "type": "boolean",
                    "optional": True
                }
            },
            "required": [
                "label",
                "value"
            ]
        }
    },
    "source": {
        "type": "string",
        "maxLength": 120,
        "optional": True
    }
}

# ─── Content area + row geometry (CSS px) ─────────────────────────────────
# Canvas is 1920×1080. Header stack occupies y<460; bars live in the
# content area below. Row spacing 80 px gives 4 rows in ~320 px, with
# room for the source caption at the bottom.
CONTENT_X = 100
CONTENT_W = 1720
BARS_Y = 500             # first row top — leaves air below the header
ROW_SPACING = 80
BAR_H = 50
LABEL_W = 180
LABEL_GAP = 24
VALUE_W = 120
VALUE_GAP = 16
SOURCE_Y = 990

# Per-bar idx offsets. idx_base = 20 + i*4; +0 = label, +1 = value.
# +2 / +3 are reserved (so extension to accent/delta later doesn't shift
# existing placeholders).
N_BARS = 4

# Sample content — mirrors the HTML reference (Share of revenue by region)
# so the demo slide + the layout prompt text read consistently. Users
# editing fresh slides see these as prompt text.
SAMPLE_BARS: list[tuple[str, float, bool]] = [
    ("EMEA",  62, False),
    ("NAM",   24, True),
    ("APAC",  11, False),
    ("LATAM", 3,  False),
]


def build(layout):
    set_layout_name(layout, NAME)
    set_layout_background(layout, T.HEX[BG])
    paint_chrome(layout, variant="light", pgmeta=PGMETA)

    content_header(layout, eyebrow=EYEBROW_PROMPT, title=TITLE_PROMPT)

    # Total bbox for the component — covers all N_BARS rows.
    bars_h = N_BARS * ROW_SPACING

    # Paint the decorative bar geometry + hairlines.
    add_graphical_bars(
        layout,
        x_px=CONTENT_X,
        y_px=BARS_Y,
        w_px=CONTENT_W,
        h_px=bars_h,
        bars=SAMPLE_BARS,
        label_w_px=LABEL_W,
        value_w_px=VALUE_W,
        bar_h_px=BAR_H,
        row_spacing_px=ROW_SPACING,
    )

    # Geometry shared between the text-placeholder calls and the component
    # so label + bar + value line up (the component computes the same
    # values internally — we re-derive here to position placeholders).
    bar_x = CONTENT_X + LABEL_W + LABEL_GAP
    value_x = CONTENT_X + CONTENT_W - VALUE_W
    # Row vertical geometry — keep in sync with add_graphical_bars internals.
    # bar_y = row_y + (row_spacing - bar_h) // 2 - 8
    row_pad_top = (ROW_SPACING - BAR_H) // 2 - 8

    for i, (label, value, _accent) in enumerate(SAMPLE_BARS[:N_BARS]):
        row_y = BARS_Y + i * ROW_SPACING
        bar_y = row_y + row_pad_top
        idx_base = 20 + i * 4

        # LABEL — left column, mono uppercase, vertically centred on the bar.
        add_text_placeholder(
            layout, idx=idx_base, name=f"Bar {i+1} Label", ph_type="body",
            x_px=CONTENT_X, y_px=bar_y + (BAR_H - 28) // 2,
            w_px=LABEL_W, h_px=28,
            prompt_text=label,
            size_px=T.SIZE_PX["bar_label"], weight="medium",
            color=T.BLACK,
        )

        # VALUE — right column, mono, right-aligned, vertically centred on bar.
        add_text_placeholder(
            layout, idx=idx_base + 1, name=f"Bar {i+1} Value", ph_type="body",
            x_px=value_x, y_px=bar_y + (BAR_H - 28) // 2,
            w_px=VALUE_W, h_px=28,
            prompt_text=f"{value:g}%",
            size_px=T.SIZE_PX["bar_num"], font=T.FONT_MONO,
            color=T.BLACK, align="r",
        )

    # ── Source caption ───────────────────────────────────────────────────
    add_text_placeholder(
        layout, idx=60, name="Source", ph_type="body",
        x_px=CONTENT_X, y_px=SOURCE_Y, w_px=CONTENT_W, h_px=24,
        prompt_text="Figure 01 · Internal finance, Q3 2025 · N = €14.1 bn",
        size_px=14, font=T.FONT_MONO,
        color=T.GRAPHITE, uppercase=True, tracking_em=0.1,
    )
