#!/usr/bin/env python3
"""Build the pipeline's block in each UTC day's daily note — deterministic, no model call.

    uv run scripts/daily_build.py [--dry-run] [--json] [--today YYYY-MM-DD]

`00_Daily/<YYYY-MM-DD>.md` is the note Obsidian's Daily notes and Calendar plugins open for a
day, so the Calendar becomes a click-through history of what the pipeline did. The day is the
UTC day, the same one `distilled_at`/`processed_date` carry: an evening in CEST lands on the
next day's note, and the block says so.

The note is also the owner's: he may write in it before or after a run. This script owns only
the block between `%% daily:start %%` and `%% daily:end %%` and replaces just that, every byte
outside it untouched. A note without the markers gets the block appended at its end; a missing
note is created with minimal frontmatter and the block; a note with a start and no end (or more
than one of either) is left alone and reported in a DLQ note.

    Distilled today      notes distilled that UTC day (`vault_utils.distilled_when`: a distilled
                         note's `distilled_at`, else `processed_date`; never an estimated one),
                         newest first
    Changed today        notes whose `updated_at` falls on the day and that were not distilled on it
    Bubbles today        the radar's briefing for the day, copied in (00_Memory/radar/Bubbles-<day>.md:
                         each bubble's promotions, held and missed items, heaviest first; its headings
                         one level down, never a link into 00_Memory); left out when there is none
    Radar today          the day's strong radar items (00_Memory/radar/state.jsonl)
    Pipeline runs today  the day's run rows in 00_Memory/imports.jsonl (`imports_log.runs`, the
                         same numbers Imports.md and the run report show); only a vault whose ledger
                         has no run row yet falls back to its `pipeline …` commits plus the run in
                         progress (pipeline-state.json's last_run), saying so when history is
                         shallow; left out when there are none
    Stuck today          DLQ notes created that day and still `status: active`; left out when
                         there are none

Each run rebuilds today's block, and yesterday's when its note or block is missing or today's
note has no block yet (the first run of a new day, so a run that finished after midnight UTC
and the `→` link still reach it); never a day further back.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import UTC, date, datetime, timedelta
from pathlib import Path

import imports_log
from imports_log import COUNTS, RUN_SUBJECT
from now_build import _obsidian_uri
from pipeline_run import STATE
from vault_utils import (
    atomic_write,
    contained,
    discover_notes,
    distilled_when,
    one_line,
    read_frontmatter,
    read_jsonl,
    require_vault,
    shallow_history,
    title_of,
    write_dlq_note,
)
from vault_utils import utc_text as _utc

DAILY = "00_Daily"
START, END = "%% daily:start %%", "%% daily:end %%"
GENERATOR = "daily_build.py"
CONTENT = ("02_Projects/", "03_Areas/", "04_Resources/")
RADAR_SHOW = 10
TITLE_CHARS, DESC_CHARS = 120, 160
HEADER = (
    f"> Generated by `{GENERATOR}` on every pipeline run. Everything between the `daily:` markers is "
    "replaced each time; write above or below them."
)
_WIKILINK = re.compile(r"\[\[([^\]|]+\|)?([^\]]+)\]\]")
_UNLINKABLE = re.compile(r"[#^\[\]|]")  # a path with one of these cannot be a wikilink target


def _text(value: object, limit: int) -> str:
    """Someone else's words as one line of plain text inside the block: an embedded wikilink is
    reduced to its label (it would be a dead link here), and `%%` (an Obsidian comment, and the
    markers' own syntax) is broken up."""
    text = re.sub(r"%{2,}", "%", _WIKILINK.sub(r"\2", str(value or "")).replace("[[", "(").replace("]]", ")"))
    return one_line(text, limit)


def _link(vault: Path, rel: str, title: str) -> str:
    """`[[path|Title]]` with the alias made safe; a path no wikilink can reach gets the title and
    an `obsidian://` link instead."""
    label = _text(title, TITLE_CHARS).replace("|", "-").replace("[", "(").replace("]", ")")
    rel = rel.removesuffix(".md")
    if _UNLINKABLE.search(rel):
        return f"{label} ([open]({_obsidian_uri(vault, rel)}))"
    return f"[[{rel}|{label}]]"


def _clock(when: str) -> str:
    return when[11:16] + " " if len(when) > 10 else ""


def notes(vault: Path) -> list[tuple[str, dict, str]]:
    """(path, frontmatter, title) of every content note under 02–04, the only folders a daily
    note links into."""
    out = []
    for p in discover_notes(vault):
        rel = p.relative_to(vault).as_posix()
        if rel.startswith(CONTENT):
            fm, body = read_frontmatter(p)
            out.append((rel, fm, title_of(fm, body, p.stem)))
    return out


def bubbles(vault: Path, day: str) -> list[str]:
    """The radar's Bubbles briefing of the day as lines of this block: its body without frontmatter
    or title, headings two levels down (## → ####), markers and link syntax left as the radar wrote
    them. [earned: 2026-09-30 — the owner wants the weighted day in the vault, not only online]"""
    path = vault / "00_Memory" / "radar" / f"Bubbles-{day}.md"
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return []
    if text.startswith("---"):
        text = text.split("\n---", 1)[-1]
    body = [ln for ln in text.splitlines() if not ln.startswith("# ") and "%%" not in ln]
    body = ["##" + ln if ln.startswith("#") else ln for ln in body]
    while body and not body[0].strip():
        body.pop(0)
    while body and not body[-1].strip():
        body.pop()
    return (["### Bubbles today", ""] + body + [""]) if body else []


def radar(vault: Path, day: str) -> list[dict]:
    """The day's strong radar items, one per item (its best score), strongest first — now_build's
    `radar()` for a single day."""
    best: dict[str, dict] = {}
    for row in read_jsonl(vault / "00_Memory" / "radar" / "state.jsonl"):
        if not row.get("strong") or str(row.get("run", ""))[:10] != day:
            continue
        row["score"] = max((row.get("p") or {}).get(t, 0) for t in row["strong"])
        key = row.get("canonical") or row.get("url")
        if key not in best or row["score"] > best[key]["score"]:
            best[key] = row
    return sorted(best.values(), key=lambda r: (-r["score"], str(r.get("title"))))


def runs(vault: Path, day: date) -> tuple[list[tuple[str, int | None, int | None, int | None]], dict, str]:
    """([(HH:MM, distilled, dropped, failed)], the day's totals, a caveat) for `day`. From the
    ledger's run rows (`imports_log`; counts None for a legacy row whose counts were not recorded),
    whose `end` writes this run's row before building this. A vault with no run row at all falls
    back to its `pipeline YYYY-MM-DD HH:MM: …` commits plus pipeline-state.json's `last_run` (the
    run building this, not committed yet), with a caveat when that history is shallow."""
    ledger = imports_log.runs(vault)
    if ledger:
        mine = sorted((r for r in ledger if r["run"][:10] == day.isoformat()), key=lambda r: r["run"])
        rows = [(r["run"][11:], *((r["distilled"], r["dropped"], r["failed"]) if r["counted"] else (None,) * 3)) for r in mine]
        return rows, imports_log.day_totals(ledger, day.isoformat()), ""
    found: dict[str, tuple[int, int, int]] = {}
    if (vault / ".git").exists():
        git = subprocess.run(
            ["git", "-C", str(vault), "log", f"--grep=^pipeline {day.isoformat()} ", "--format=%s"],
            capture_output=True,
            text=True,
            check=False,
        )
        for subject in git.stdout.splitlines():
            stamp, counts = RUN_SUBJECT.match(subject), COUNTS.search(subject)
            if stamp and counts and stamp.group(1).startswith(day.isoformat()):
                found[stamp.group(1)] = tuple(int(n) for n in counts.groups())
    try:
        last = json.loads((vault / STATE).read_text(encoding="utf-8")).get("last_run") or {}
    except (OSError, json.JSONDecodeError):
        last = {}
    stamp = _utc(str(last.get("at", "")))[:16].replace("T", " ")
    if stamp.startswith(day.isoformat()) and stamp not in found:
        found[stamp] = (int(last.get("distilled") or 0), int(last.get("dropped") or 0), int(last.get("failed") or 0))
    rows = [(s[11:], *found[s]) for s in sorted(found)]
    totals = {"runs": len(rows), **{k: sum(r[i] for r in rows) for i, k in ((1, "distilled"), (2, "dropped"), (3, "failed"))},
              "uncounted": 0}
    caveat = "counted from git, whose history in this checkout is shallow: a floor, not a total" if rows and shallow_history(vault) else ""
    return rows, totals, caveat


def stuck(vault: Path, day: str) -> list[str]:
    """DLQ notes created on `day` and still `status: active` (now_build's rule: a resolved note is
    not stuck): 00_Memory/, so plain text and an `obsidian://` link. [earned: 2026-09-29 audit — a
    resolved DLQ note was listed as stuck]"""
    out = []
    for p in contained(sorted((vault / "00_Memory" / "dlq").glob("*.md")), vault):
        fm, body = read_frontmatter(p)
        created = _utc(fm.get("created"))[:10] or p.name[:10]
        if created == day and str(fm.get("status", "active")) == "active":
            rel = p.relative_to(vault).with_suffix("").as_posix()
            title = _text(fm.get("description") or title_of(fm, body, p.stem), TITLE_CHARS)
            out.append(f"- {title} ([open]({_obsidian_uri(vault, rel)}))")
    return out


def block(vault: Path, day: date, content: list[tuple[str, dict, str]], exists: set[str]) -> tuple[str, dict]:
    """The block for `day`, markers included, and its counts. `exists`: the days with a note."""
    d = day.isoformat()

    def on_day(when_of) -> list[tuple[str, str, dict, str]]:  # newest first, ties by path
        dated = sorted((when_of(fm), rel, fm, title) for rel, fm, title in content)
        return sorted((n for n in dated if n[0][:10] == d), key=lambda n: n[0], reverse=True)

    distilled = on_day(distilled_when)
    done = {rel for _, rel, _, _ in distilled}
    changed = [n for n in on_day(lambda fm: _utc(fm.get("updated_at"))) if n[1] not in done]
    strong = radar(vault, d)
    ran, totals, caveat = runs(vault, day)
    dlq = stuck(vault, d)

    def line(when: str, rel: str, fm: dict, title: str) -> str:
        desc = _text(fm.get("description"), DESC_CHARS)
        return f"- {_clock(when)}{_link(vault, rel, title)}" + (f" — {desc}" if desc else "")

    out = [START, f"## Pipeline, {d} (UTC day)", "", HEADER, ""]
    nav = [
        f"[[{DAILY}/{n.isoformat()}|{arrow}]]"
        for n, arrow in ((day - timedelta(days=1), "←"), (day + timedelta(days=1), "→"))
        if n.isoformat() in exists
    ]
    if nav:
        out += [" · ".join(nav), ""]
    out += (
        [f"### Distilled today ({len(distilled)})", ""]
        + ([line(*n) for n in distilled] or ["- Nothing distilled"])
        + [""]
    )
    out += [f"### Changed today ({len(changed)})", ""] + ([line(*n) for n in changed] or ["- (none)"]) + [""]
    out += bubbles(vault, d)
    radar_lines = [
        f"- [{_text(r.get('title') or r.get('url'), TITLE_CHARS).replace('[', '(').replace(']', ')')}]"
        f"({str(r.get('url') or '').replace(' ', '%20').replace(')', '%29')}) — {_text(', '.join(r['strong']), 80)}"
        for r in strong
    ]
    radar_lines = radar_lines[:RADAR_SHOW] + (
        [f"- … and {len(strong) - RADAR_SHOW} more"] if len(strong) > RADAR_SHOW else []
    )
    out += [f"### Radar today ({len(strong)})", ""] + (radar_lines or ["- (none)"]) + [""]
    if ran:
        out += [
            f"### Pipeline runs today ({totals['runs']})",
            "",
            f"- In all: {totals['distilled']} distilled, {totals['dropped']} dropped, {totals['failed']} failed"
            + (f" ({totals['uncounted']} run(s) without recorded counts)" if totals["uncounted"] else "")
            + (f" — {caveat}" if caveat else ""),
        ]
        out += [
            f"- {t} UTC: " + (f"{a} distilled, {b} dropped, {c} failed" if a is not None else "counts not recorded")
            for t, a, b, c in ran
        ] + [""]
    if dlq:
        out += [f"### Stuck today ({len(dlq)})", ""] + dlq + [""]
    out[-1] = END
    stats = {
        "distilled": len(distilled),
        "changed": len(changed),
        "radar": len(strong),
        "runs": len(ran),
        "stuck": len(dlq),
    }
    return "\n".join(out), stats


def _span(text: str) -> tuple[int, int] | None | str:
    """Where the block sits in `text` (start, end past the end marker); None with no markers at
    all; "malformed" for anything but exactly one start followed by exactly one end."""
    if START not in text and END not in text:
        return None
    s, e = text.find(START), text.find(END)
    if text.count(START) != 1 or text.count(END) != 1 or e < s:
        return "malformed"
    return s, e + len(END)


def _read(path: Path) -> str | None:
    """The note's exact text (no newline translation, so CRLF survives), or None if absent."""
    return path.read_bytes().decode("utf-8") if path.is_file() else None


def build(vault: Path, today: date) -> tuple[dict[str, str], dict]:
    folder = vault / DAILY
    yesterday = today - timedelta(days=1)
    texts: dict[date, str | None] = {}
    unreadable: set[date] = set()
    for day in (today, yesterday):
        try:
            texts[day] = _read(folder / f"{day.isoformat()}.md")
        except (OSError, UnicodeDecodeError):
            texts[day] = ""
            unreadable.add(day)
    y, t = texts[yesterday], texts[today]
    days = [today]
    if y is None or not isinstance(_span(y), tuple) or t is None or START not in t:
        days.insert(0, yesterday)
    exists = {p.stem for p in contained(folder.glob("*.md"), vault)} | {d.isoformat() for d in days}
    content = notes(vault)

    files: dict[str, str] = {}
    malformed: list[str] = []
    stats: dict = {"days": [d.isoformat() for d in days]}
    for day in days:
        rel, text = f"{DAILY}/{day.isoformat()}.md", texts[day]
        span = _span(text) if text is not None else None
        if span == "malformed" or day in unreadable:
            malformed.append(rel)
            continue
        new, counts = block(vault, day, content, exists)
        if day == today:
            stats.update(counts)
        if text is None:
            files[rel] = (
                f"---\ncreated: {day.isoformat()}\ndescription: What the pipeline did on {day.isoformat()} "
                f"(UTC day)\ntags:\n  - daily\n---\n\n{new}\n"
            )
            continue
        if "\r\n" in text:
            new = new.replace("\n", "\r\n")
        nl = "\r\n" if "\r\n" in text else "\n"
        if span is None:
            sep = "" if not text or text.endswith(nl * 2) else nl if text.endswith(nl) else nl * 2
            files[rel] = text + sep + new + nl
        else:
            files[rel] = text[: span[0]] + new + text[span[1] :]
    stats["malformed"] = malformed
    return files, stats


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Build the pipeline's block in today's (and yesterday's) daily note")
    ap.add_argument("--dry-run", action="store_true", help="report what would be written, write nothing")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--today", default=None, help="YYYY-MM-DD, a UTC day (default: today in UTC)")
    args = ap.parse_args(argv)
    vault = require_vault()
    files, stats = build(vault, date.fromisoformat(args.today) if args.today else datetime.now(UTC).date())
    changed = [
        r for r, t in files.items() if not (vault / r).is_file() or (vault / r).read_bytes() != t.encode("utf-8")
    ]
    if not args.dry_run:
        for rel in changed:
            atomic_write(vault / rel, files[rel])
        for rel in stats["malformed"]:
            write_dlq_note(
                vault,
                slug=f"daily-markers-{Path(rel).stem}",
                title=f"{rel}: the pipeline's block markers are broken",
                what_happened=f"{rel} has `{START}` / `{END}` markers that are not exactly one start followed by "
                f"one end (or the file is not UTF-8); {GENERATOR} left the file untouched.",
                why_recorded="The daily note is also the owner's own; guessing where the generated block ends "
                "could overwrite what he wrote.",
                resolution=f"Fix or delete the markers in {rel} (with none, the next run appends a fresh block "
                "at the end), then mark this note resolved.",
                confidence="high",
            )
    stats["would_change" if args.dry_run else "changed"] = changed
    print(
        json.dumps(stats, indent=2)
        if args.json
        else f"daily notes {', '.join(stats['days'])}: today {stats.get('distilled', 0)} distilled, "
        f"{stats.get('changed', 0)} changed, {stats.get('radar', 0)} radar, {stats.get('runs', 0)} runs; "
        f"{len(stats['malformed'])} malformed; {'would change' if args.dry_run else 'changed'} {len(changed)} files"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
