#!/usr/bin/env python3
"""Build the pipeline's block in each UTC day's daily note — deterministic, no model call.

    uv run scripts/daily_build.py [--dry-run] [--json] [--today YYYY-MM-DD]

`00_Daily/<YYYY-MM-DD>.md` is the note Obsidian's Daily notes and Calendar plugins open for a
day, so the Calendar becomes a click-through history of what the pipeline did. The day is the
UTC day, the same one `distilled_at`/`processed_date` carry: an evening in CEST lands on the
next day's note, and the block says so.

The note is also the owner's: he may write in it before or after a run. This script owns only
the block between `%% daily:start %%` and `%% daily:end %%` and replaces just that, every byte
outside it untouched. A note without the markers gets the block appended at its end; a missing
note is created with minimal frontmatter and the block; a note with a start and no end (or more
than one of either) is left alone and reported in a DLQ note.

    Distilled today      notes distilled that UTC day (`distilled_at`, else `processed_date`;
                         never an estimated one), newest first
    Changed today        notes whose `updated_at` falls on the day and that were not distilled on it
    Radar today          the day's strong radar items (00_Memory/radar/state.jsonl)
    Pipeline runs today  the day's `pipeline …` commits plus the run in progress
                         (pipeline-state.json's last_run); left out when there are none
    Stuck today          DLQ notes created that day; left out when there are none

Each run rebuilds today's block, and yesterday's when its note or block is missing or today's
note has no block yet (the first run of a new day, so a run that finished after midnight UTC
and the `→` link still reach it); never a day further back.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import UTC, date, datetime, timedelta
from pathlib import Path

from dashboard_build import RUN
from imports_log import RUN_SUBJECT
from now_build import _obsidian_uri
from pipeline_run import STATE
from vault_utils import (
    atomic_write,
    contained,
    discover_notes,
    one_line,
    read_frontmatter,
    read_jsonl,
    require_vault,
    title_of,
    write_dlq_note,
)

DAILY = "00_Daily"
START, END = "%% daily:start %%", "%% daily:end %%"
GENERATOR = "daily_build.py"
CONTENT = ("02_Projects/", "03_Areas/", "04_Resources/")
RADAR_SHOW = 10
TITLE_CHARS, DESC_CHARS = 120, 160
HEADER = (
    f"> Generated by `{GENERATOR}` on every pipeline run. Everything between the `daily:` markers is "
    "replaced each time; write above or below them."
)
_WIKILINK = re.compile(r"\[\[([^\]|]+\|)?([^\]]+)\]\]")
_UNLINKABLE = re.compile(r"[#^\[\]|]")  # a path with one of these cannot be a wikilink target


def _utc(value: object) -> str:
    """A frontmatter date or timestamp as UTC text: `YYYY-MM-DDTHH:MM:SSZ`, a bare `YYYY-MM-DD`
    for a date-only value, "" for nothing or something unreadable. YAML reads an unquoted
    timestamp as a `datetime` (and one with an offset must be moved to UTC before taking its day)."""
    if isinstance(value, str):
        text = value.strip()
        try:
            value = datetime.fromisoformat(text) if len(text) > 10 else date.fromisoformat(text)
        except ValueError:
            return ""
    if isinstance(value, datetime):
        moment = value.replace(tzinfo=UTC) if value.tzinfo is None else value.astimezone(UTC)
        return moment.strftime("%Y-%m-%dT%H:%M:%SZ")
    return value.isoformat() if isinstance(value, date) else ""


def distilled_when(fm: dict) -> str:
    """When a note was distilled, in UTC: `distilled_at` unless estimated, else `processed_date`
    unless estimated, else ""."""
    if fm.get("distilled_at_estimated") is not True and (when := _utc(fm.get("distilled_at"))):
        return when
    return _utc(fm.get("processed_date")) if fm.get("processed_date_estimated") is not True else ""


def _text(value: object, limit: int) -> str:
    """Someone else's words as one line of plain text inside the block: an embedded wikilink is
    reduced to its label (it would be a dead link here), and `%%` (an Obsidian comment, and the
    markers' own syntax) is broken up."""
    text = re.sub(r"%{2,}", "%", _WIKILINK.sub(r"\2", str(value or "")).replace("[[", "(").replace("]]", ")"))
    return one_line(text, limit)


def _link(vault: Path, rel: str, title: str) -> str:
    """`[[path|Title]]` with the alias made safe; a path no wikilink can reach gets the title and
    an `obsidian://` link instead."""
    label = _text(title, TITLE_CHARS).replace("|", "-").replace("[", "(").replace("]", ")")
    rel = rel.removesuffix(".md")
    if _UNLINKABLE.search(rel):
        return f"{label} ([open]({_obsidian_uri(vault, rel)}))"
    return f"[[{rel}|{label}]]"


def _clock(when: str) -> str:
    return when[11:16] + " " if len(when) > 10 else ""


def notes(vault: Path) -> list[tuple[str, dict, str]]:
    """(path, frontmatter, title) of every content note under 02–04, the only folders a daily
    note links into."""
    out = []
    for p in discover_notes(vault):
        rel = p.relative_to(vault).as_posix()
        if rel.startswith(CONTENT):
            fm, body = read_frontmatter(p)
            out.append((rel, fm, title_of(fm, body, p.stem)))
    return out


def radar(vault: Path, day: str) -> list[dict]:
    """The day's strong radar items, one per item (its best score), strongest first — now_build's
    `radar()` for a single day."""
    best: dict[str, dict] = {}
    for row in read_jsonl(vault / "00_Memory" / "radar" / "state.jsonl"):
        if not row.get("strong") or str(row.get("run", ""))[:10] != day:
            continue
        row["score"] = max((row.get("p") or {}).get(t, 0) for t in row["strong"])
        key = row.get("canonical") or row.get("url")
        if key not in best or row["score"] > best[key]["score"]:
            best[key] = row
    return sorted(best.values(), key=lambda r: (-r["score"], str(r.get("title"))))


def runs(vault: Path, day: date) -> list[tuple[str, int, int, int]]:
    """(HH:MM, distilled, dropped, failed) per run on `day`: its `pipeline YYYY-MM-DD HH:MM: …`
    commits (the stamp is the run's UTC `now`), plus pipeline-state.json's `last_run` — the run
    whose `end` is building this, not committed yet — under the same stamp."""
    found: dict[str, tuple[int, int, int]] = {}
    if (vault / ".git").exists():
        git = subprocess.run(
            ["git", "-C", str(vault), "log", f"--grep=^pipeline {day.isoformat()} ", "--format=%s"],
            capture_output=True,
            text=True,
            check=False,
        )
        for subject in git.stdout.splitlines():
            stamp, counts = RUN_SUBJECT.match(subject), RUN.search(subject)
            if stamp and counts and stamp.group(1).startswith(day.isoformat()):
                found[stamp.group(1)] = tuple(int(n) for n in counts.groups())
    try:
        last = json.loads((vault / STATE).read_text(encoding="utf-8")).get("last_run") or {}
    except (OSError, json.JSONDecodeError):
        last = {}
    stamp = _utc(str(last.get("at", "")))[:16].replace("T", " ")
    if stamp.startswith(day.isoformat()) and stamp not in found:
        found[stamp] = (int(last.get("distilled") or 0), int(last.get("dropped") or 0), int(last.get("failed") or 0))
    return [(s[11:], *found[s]) for s in sorted(found)]


def stuck(vault: Path, day: str) -> list[str]:
    """DLQ notes created on `day`: 00_Memory/, so plain text and an `obsidian://` link."""
    out = []
    for p in contained(sorted((vault / "00_Memory" / "dlq").glob("*.md")), vault):
        fm, body = read_frontmatter(p)
        created = _utc(fm.get("created"))[:10] or p.name[:10]
        if created == day:
            rel = p.relative_to(vault).with_suffix("").as_posix()
            title = _text(fm.get("description") or title_of(fm, body, p.stem), TITLE_CHARS)
            state = str(fm.get("status", "active"))
            out.append(
                f"- {title} ([open]({_obsidian_uri(vault, rel)}))" + ("" if state == "active" else f" · {state}")
            )
    return out


def block(vault: Path, day: date, content: list[tuple[str, dict, str]], exists: set[str]) -> tuple[str, dict]:
    """The block for `day`, markers included, and its counts. `exists`: the days with a note."""
    d = day.isoformat()

    def on_day(when_of) -> list[tuple[str, str, dict, str]]:  # newest first, ties by path
        dated = sorted((when_of(fm), rel, fm, title) for rel, fm, title in content)
        return sorted((n for n in dated if n[0][:10] == d), key=lambda n: n[0], reverse=True)

    distilled = on_day(distilled_when)
    done = {rel for _, rel, _, _ in distilled}
    changed = [n for n in on_day(lambda fm: _utc(fm.get("updated_at"))) if n[1] not in done]
    strong = radar(vault, d)
    ran = runs(vault, day)
    dlq = stuck(vault, d)

    def line(when: str, rel: str, fm: dict, title: str) -> str:
        desc = _text(fm.get("description"), DESC_CHARS)
        return f"- {_clock(when)}{_link(vault, rel, title)}" + (f" — {desc}" if desc else "")

    out = [START, f"## Pipeline, {d} (UTC day)", "", HEADER, ""]
    nav = [
        f"[[{DAILY}/{n.isoformat()}|{arrow}]]"
        for n, arrow in ((day - timedelta(days=1), "←"), (day + timedelta(days=1), "→"))
        if n.isoformat() in exists
    ]
    if nav:
        out += [" · ".join(nav), ""]
    out += (
        [f"### Distilled today ({len(distilled)})", ""]
        + ([line(*n) for n in distilled] or ["- Nothing distilled"])
        + [""]
    )
    out += [f"### Changed today ({len(changed)})", ""] + ([line(*n) for n in changed] or ["- (none)"]) + [""]
    radar_lines = [
        f"- [{_text(r.get('title') or r.get('url'), TITLE_CHARS).replace('[', '(').replace(']', ')')}]"
        f"({str(r.get('url') or '').replace(' ', '%20').replace(')', '%29')}) — {_text(', '.join(r['strong']), 80)}"
        for r in strong
    ]
    radar_lines = radar_lines[:RADAR_SHOW] + (
        [f"- … and {len(strong) - RADAR_SHOW} more"] if len(strong) > RADAR_SHOW else []
    )
    out += [f"### Radar today ({len(strong)})", ""] + (radar_lines or ["- (none)"]) + [""]
    if ran:
        totals = [sum(r[i] for r in ran) for i in (1, 2, 3)]
        out += [
            f"### Pipeline runs today ({len(ran)})",
            "",
            f"- In all: {totals[0]} distilled, {totals[1]} dropped, {totals[2]} failed",
        ]
        out += [f"- {t} UTC: {a} distilled, {b} dropped, {c} failed" for t, a, b, c in ran] + [""]
    if dlq:
        out += [f"### Stuck today ({len(dlq)})", ""] + dlq + [""]
    out[-1] = END
    stats = {
        "distilled": len(distilled),
        "changed": len(changed),
        "radar": len(strong),
        "runs": len(ran),
        "stuck": len(dlq),
    }
    return "\n".join(out), stats


def _span(text: str) -> tuple[int, int] | None | str:
    """Where the block sits in `text` (start, end past the end marker); None with no markers at
    all; "malformed" for anything but exactly one start followed by exactly one end."""
    if START not in text and END not in text:
        return None
    s, e = text.find(START), text.find(END)
    if text.count(START) != 1 or text.count(END) != 1 or e < s:
        return "malformed"
    return s, e + len(END)


def _read(path: Path) -> str | None:
    """The note's exact text (no newline translation, so CRLF survives), or None if absent."""
    return path.read_bytes().decode("utf-8") if path.is_file() else None


def build(vault: Path, today: date) -> tuple[dict[str, str], dict]:
    folder = vault / DAILY
    yesterday = today - timedelta(days=1)
    texts: dict[date, str | None] = {}
    unreadable: set[date] = set()
    for day in (today, yesterday):
        try:
            texts[day] = _read(folder / f"{day.isoformat()}.md")
        except (OSError, UnicodeDecodeError):
            texts[day] = ""
            unreadable.add(day)
    y, t = texts[yesterday], texts[today]
    days = [today]
    if y is None or not isinstance(_span(y), tuple) or t is None or START not in t:
        days.insert(0, yesterday)
    exists = {p.stem for p in contained(folder.glob("*.md"), vault)} | {d.isoformat() for d in days}
    content = notes(vault)

    files: dict[str, str] = {}
    malformed: list[str] = []
    stats: dict = {"days": [d.isoformat() for d in days]}
    for day in days:
        rel, text = f"{DAILY}/{day.isoformat()}.md", texts[day]
        span = _span(text) if text is not None else None
        if span == "malformed" or day in unreadable:
            malformed.append(rel)
            continue
        new, counts = block(vault, day, content, exists)
        if day == today:
            stats.update(counts)
        if text is None:
            files[rel] = (
                f"---\ncreated: {day.isoformat()}\ndescription: What the pipeline did on {day.isoformat()} "
                f"(UTC day)\ntags:\n  - daily\n---\n\n{new}\n"
            )
            continue
        if "\r\n" in text:
            new = new.replace("\n", "\r\n")
        nl = "\r\n" if "\r\n" in text else "\n"
        if span is None:
            sep = "" if not text or text.endswith(nl * 2) else nl if text.endswith(nl) else nl * 2
            files[rel] = text + sep + new + nl
        else:
            files[rel] = text[: span[0]] + new + text[span[1] :]
    stats["malformed"] = malformed
    return files, stats


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Build the pipeline's block in today's (and yesterday's) daily note")
    ap.add_argument("--dry-run", action="store_true", help="report what would be written, write nothing")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--today", default=None, help="YYYY-MM-DD, a UTC day (default: today in UTC)")
    args = ap.parse_args(argv)
    vault = require_vault()
    files, stats = build(vault, date.fromisoformat(args.today) if args.today else datetime.now(UTC).date())
    changed = [
        r for r, t in files.items() if not (vault / r).is_file() or (vault / r).read_bytes() != t.encode("utf-8")
    ]
    if not args.dry_run:
        for rel in changed:
            atomic_write(vault / rel, files[rel])
        for rel in stats["malformed"]:
            write_dlq_note(
                vault,
                slug=f"daily-markers-{Path(rel).stem}",
                title=f"{rel}: the pipeline's block markers are broken",
                what_happened=f"{rel} has `{START}` / `{END}` markers that are not exactly one start followed by "
                f"one end (or the file is not UTF-8); {GENERATOR} left the file untouched.",
                why_recorded="The daily note is also the owner's own; guessing where the generated block ends "
                "could overwrite what he wrote.",
                resolution=f"Fix or delete the markers in {rel} (with none, the next run appends a fresh block "
                "at the end), then mark this note resolved.",
                confidence="high",
            )
    stats["would_change" if args.dry_run else "changed"] = changed
    print(
        json.dumps(stats, indent=2)
        if args.json
        else f"daily notes {', '.join(stats['days'])}: today {stats.get('distilled', 0)} distilled, "
        f"{stats.get('changed', 0)} changed, {stats.get('radar', 0)} radar, {stats.get('runs', 0)} runs; "
        f"{len(stats['malformed'])} malformed; {'would change' if args.dry_run else 'changed'} {len(changed)} files"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
