#!/usr/bin/env python3
"""What every pipeline run imported, and what became of each item: `Imports.md`, one file.

    uv run scripts/imports_log.py [build]        rebuild Imports.md (a generator in `end`)
    uv run scripts/imports_log.py backfill       seed the log from the vault's git history, once

`end` records each run's new Readwise ledger rows (the rows appended since `begin`) in
`00_Memory/imports.jsonl`, one line per run: `{"run": "YYYY-MM-DD HH:MM", "items": [...]}`, with
what the capture said at the time (title, source, category, author, enrichment, media). What became
of each item is looked up at every build, so the page stays true as captures move on:

    distilled   retired to 05_Archive/, its manifest line names the note(s) it became
    dropped     retired without a note (radar and newsletter captures only)
    duplicate   retired as a copy of another capture or note, kept whole
    archived    in the archive whole, but no manifest line says what it became (retired by hand)
    known       found already in the vault at ingest
    waiting     still in 01_Capture/ (with its failed attempts, if any)
    missing     nowhere in the vault: a clipping was lost, and the page says so first

Runs are sections headed by their date and time, newest first. [earned: 2026-09-25, owner's
request — keep a list of what each run imported, in one file, sorted by date and time]
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

from vault_utils import atomic_write, contained, read_frontmatter, require_vault

LOG = Path("00_Memory") / "imports.jsonl"
INGESTED = Path("00_Memory") / "readwise-ingested.jsonl"
STATE = Path("00_Memory") / "pipeline-state.json"
PAGE = "Imports.md"
RUN_SUBJECT = re.compile(r"^pipeline (\d{4}-\d{2}-\d{2} \d{2}:\d{2})")
WIKILINK = re.compile(r"\[\[([^\]|#]+)(?:[^\]]*)\]\]")
LABEL = {"tweet": "Tweet", "article": "Article", "video": "Video", "email": "Newsletter", "pdf": "PDF",
         "epub": "EPUB", "rss": "Feed", "podcast": "Podcast"}
HEADER = ("> Generated by `imports_log.py` at the end of every pipeline run from `00_Memory/imports.jsonl`. "
          "Never edit it by hand.")


def _capture_file(vault: Path, capture: str) -> Path | None:
    """Where a capture is now: still in the inbox, or retired whole to the archive."""
    if not capture:
        return None
    here = vault / capture
    if here.is_file():
        return here
    stem = Path(capture).stem
    hits = [p for p in contained((vault / "05_Archive").glob(f"*/{stem}--FULLCAPTURE.md"), vault) if p.is_file()]
    return hits[0] if hits else None


def describe(vault: Path, row: dict) -> dict:
    """One ledger row as a log item: the row, plus what its capture says about the clipping."""
    item = {k: row[k] for k in ("doc_id", "capture", "via", "found", "duplicate_of") if row.get(k)}
    path = _capture_file(vault, row.get("capture", ""))
    if path:
        fm, body = read_frontmatter(path)
        h1 = re.search(r"^# (.+)$", body, re.M)
        item |= {k: v for k, v in {
            "title": (h1.group(1).strip() if h1 else Path(row["capture"]).stem)[:200],
            "source": fm.get("source") if isinstance(fm.get("source"), str) else None,
            "category": fm.get("category"), "author": str(fm.get("author") or "")[:80] or None,
            "enrichment": fm.get("enrichment"), "media": len(fm.get("media") or []) or None,
        }.items() if v}
    return item


def record(vault: Path, run: str, rows: list[dict]) -> dict:
    """Append this run's imports to the log (every run, an empty one too: a quiet run is a fact)."""
    entry = {"run": run, "items": [describe(vault, r) for r in rows]}
    path = vault / LOG
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    return entry


def load(vault: Path) -> list[dict]:
    runs: dict[str, dict] = {}
    path = vault / LOG
    if path.is_file():
        for line in path.read_text(encoding="utf-8").splitlines():
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(entry, dict) and entry.get("run"):
                runs.setdefault(entry["run"], {"run": entry["run"], "items": []})["items"] += entry.get("items") or []
    return sorted(runs.values(), key=lambda r: r["run"], reverse=True)


def _manifests(vault: Path) -> dict[str, str]:
    """Archived capture file name → its manifest line."""
    lines: dict[str, str] = {}
    for readme in contained((vault / "05_Archive").glob("*/README.md"), vault):
        for line in readme.read_text(encoding="utf-8", errors="replace").splitlines():
            m = re.match(r"^- `([^`]+)` — (.*)$", line)
            if m:
                lines[m.group(1)] = m.group(2)
    return lines


def fate(vault: Path, item: dict, manifests: dict[str, str], attempts: dict[str, int]) -> dict:
    """{status, notes, detail} for one item, from where things are now."""
    if item.get("duplicate_of"):
        return {"status": "duplicate", "notes": [], "detail": f"a second save of {item['duplicate_of']}"}
    if item.get("found"):
        ok = (vault / item["found"]).is_file()
        return {"status": "known" if ok else "missing", "notes": [item["found"]] if ok else [],
                "detail": "already in the vault" if ok else f"{item['found']} is gone"}
    capture = item.get("capture", "")
    if capture and (vault / capture).is_file():
        n = attempts.get(capture, 0)
        return {"status": "waiting", "notes": [], "detail": f"in the inbox, {n} failed attempt(s)" if n else "in the inbox"}
    line = manifests.get(f"{Path(capture).stem}--FULLCAPTURE.md") if capture else None
    if line is None:
        if _capture_file(vault, capture):
            return {"status": "archived", "notes": [], "detail": "kept whole in the archive, without a manifest line"}
        return {"status": "missing", "notes": [], "detail": "not in the inbox, not in the archive"}
    notes = [t.strip().removesuffix(".md") for t in WIKILINK.findall(line)]
    status = "duplicate" if "**duplicate**" in line else "dropped" if "**dropped**" in line else "distilled"
    detail = re.sub(r"\[\[([^\]|]+)\|([^\]]+)\]\]", r"\2", line)
    detail = re.sub(r"\[\[([^\]]+)\]\]", lambda m: m.group(1).rsplit("/", 1)[-1], detail)
    return {"status": status, "notes": notes, "detail": re.sub(r"\s+", " ", detail)[:300]}


def resolved(vault: Path) -> list[dict]:
    """Every logged run with each item's fate attached, newest first."""
    manifests = _manifests(vault)
    try:
        attempts = json.loads((vault / STATE).read_text(encoding="utf-8")).get("attempts", {})
    except (OSError, json.JSONDecodeError):
        attempts = {}
    return [{"run": r["run"], "items": [{**it, "fate": fate(vault, it, manifests, attempts)} for it in r["items"]]}
            for r in load(vault)]


def _bullet(it: dict) -> str:
    f = it["fate"]
    kind = LABEL.get(str(it.get("category") or ""), str(it.get("category") or "Item").capitalize())
    title = it.get("title") or it.get("capture") or it.get("found") or it.get("doc_id", "?")
    title = title.replace("[", "(").replace("]", ")")
    head = f"[{title}]({it['source']})" if str(it.get("source") or "").startswith("http") else title
    extras = [x for x in (it.get("author"), it.get("via"),
                          f"enrichment {it['enrichment']}" if it.get("enrichment") else None,
                          f"{it['media']} image(s)" if it.get("media") else None) if x]
    notes = " · ".join(f"[[{n}|{n.rsplit('/', 1)[-1]}]]" for n in f["notes"])
    where = {"distilled": f"→ {notes}" if notes else f"→ {f['detail']}", "known": f"→ already in the vault: {notes}",
             "dropped": f"→ dropped: {f['detail']}", "duplicate": f"→ duplicate ({f['detail']})",
             "waiting": f"→ waiting ({f['detail']})", "archived": f"→ archived ({f['detail']})", "missing": f"→ ⚠ **missing**: {f['detail']}"}[f["status"]]
    return f"- **{kind}** {head}" + (f" — {', '.join(extras)}" if extras else "") + f" {where}"


def render(vault: Path) -> str:
    runs = resolved(vault)
    items = [it for r in runs for it in r["items"]]
    count = {s: sum(1 for it in items if it["fate"]["status"] == s)
             for s in ("distilled", "known", "dropped", "duplicate", "archived", "waiting", "missing")}
    out = ["---", "description: What every pipeline run imported from Readwise and what became of each item, newest run first.",
           "status: generated", "---", "", "# Imports", "", HEADER, "",
           f"{len(items)} items in {len(runs)} runs: " + ", ".join(f"{n} {s}" for s, n in count.items() if n) + "."]
    missing = [(r["run"], it) for r in runs for it in r["items"] if it["fate"]["status"] == "missing"]
    if missing:
        out += ["", "> [!danger] Missing clippings", "> Imported, but in neither the inbox nor the archive:"]
        out += [f"> - {run}: " + _bullet(it)[2:] for run, it in missing]
    quiet: list[str] = []
    for r in runs:
        if not r["items"]:
            quiet.append(r["run"])
            continue
        if quiet:
            out += ["", f"*Nothing new in {len(quiet)} run(s) from {quiet[-1]} to {quiet[0]}.*"]
            quiet = []
        out += ["", f"## {r['run']}", "", f"{len(r['items'])} imported.", ""] + [_bullet(it) for it in r["items"]]
    if quiet:
        out += ["", f"*Nothing new in {len(quiet)} run(s) from {quiet[-1]} to {quiet[0]}.*"]
    return "\n".join(out) + "\n"


def backfill(vault: Path) -> int:
    """Seed the log from git: each `pipeline …` commit's added ledger rows are that run's imports."""
    have = {r["run"] for r in load(vault)}
    log = subprocess.run(["git", "-C", str(vault), "log", "--reverse", "--grep=^pipeline", "--format=%H%x09%s"],
                         capture_output=True, text=True, check=False).stdout
    added = 0
    for line in log.splitlines():
        sha, _, subject = line.partition("\t")
        m = RUN_SUBJECT.match(subject)
        if not m or m.group(1) in have:
            continue
        diff = subprocess.run(["git", "-C", str(vault), "show", "--format=", "-U0", sha, "--", INGESTED.as_posix()],
                              capture_output=True, text=True, check=False).stdout
        rows = []
        for d in diff.splitlines():
            if d.startswith("+{"):
                try:
                    rows.append(json.loads(d[1:]))
                except json.JSONDecodeError:
                    continue
        record(vault, m.group(1), rows)
        added += 1
    return added


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("action", nargs="?", default="build", choices=("build", "backfill"))
    args = ap.parse_args()
    vault = require_vault()
    if args.action == "backfill":
        print(f"backfilled {backfill(vault)} run(s)")
    atomic_write(vault / PAGE, render(vault))
    print(f"{PAGE}: {len(load(vault))} runs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
