#!/usr/bin/env python3
"""Build the domain maps from the notes' own tags — deterministic, no model call.

    uv run scripts/map_build.py [--dry-run] [--json] [--today YYYY-MM-DD]

One pass over the active notes (02_Projects, 03_Areas, 04_Resources) writes, under `Maps/`:

    <domain>.md       one per `domain/*` tag on at least MIN_NOTES (3) notes or with a block in
                      maps.md (a tag on one or two notes is usually a typo, and a map of two is
                      noise): Start here (the 10 most-linked notes), New (last 30 days), every
                      note grouped by `kind`, Neighbouring domains (co-tag counts)
    <domain>.canvas   the Start-here and New notes as cards, one group per kind, their links as edges
    Overview.md       every domain with its note count and newest note
    Overview.canvas   the same as cards, edges between domains that share the most notes

Intro, title and sections per domain come from `Config/toolkit/maps.md` (distilled from the old
hand-made MOCs); without it a map groups by `kind`. A file is written only when its text changes,
so an unchanged vault makes no commit. Maps are never hand-edited: the vault's rule is "no
hand-maintained MOCs" — 80 of them had gone stale. [earned: 2026-09-23, R12]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from datetime import date, timedelta
from pathlib import Path

from vault_utils import atomic_write, discover_notes, read_frontmatter, require_vault

MAPS = "Maps"
CONFIG = Path("Config") / "toolkit" / "maps.md"
GENERATOR = "map_build.py"
START_HERE = 10
NEW_DAYS = 30
MIN_NOTES = 3
NEIGHBOURS = 5
MAX_DESC = 160
WIKILINK = re.compile(r"\[\[([^\]|#^]+)")
DOMAIN_TAG = re.compile(r"^#?domain/([a-z0-9][a-z0-9_-]*)$", re.I)
HEADER = "> Generated by `map_build.py` from the notes' tags. Edit `Config/toolkit/maps.md` or the notes, never this file."

CARD_W, CARD_H, GAP, COLS = 320, 140, 40, 3


@dataclass
class Note:
    rel: str  # path without .md
    name: str
    kind: str
    description: str
    domains: list[str]
    when: str  # processed_date, else created, else ""
    links: set[str] = field(default_factory=set)


@dataclass
class MapConfig:
    title: str = ""
    intro: str = ""
    sections: list[tuple[str, list[str]]] = field(default_factory=list)
    start: list[str] = field(default_factory=list)


def _one_line(text: object, limit: int = MAX_DESC) -> str:
    text = re.sub(r"\s+", " ", str(text or "")).strip()
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def _date(value: object) -> str:
    m = re.match(r"\d{4}-\d{2}-\d{2}", str(value or ""))
    return m.group(0) if m else ""


def _tags(fm: dict) -> list[str]:
    tags = fm.get("tags") or []
    if isinstance(tags, str):
        tags = re.split(r"[,\s]+", tags)
    return [str(t) for t in tags if t]


def default_title(slug: str) -> str:
    return " ".join(w.upper() if len(w) <= 2 else w.capitalize() for w in slug.split("-"))


def read_config(vault: Path) -> dict[str, MapConfig]:
    """`## <domain>` blocks: an optional `title:` line, intro prose, and `- Name: kind, kind`
    bullets (`- Start here: [[Note]], [[Note]]` pins notes ahead of the most-linked ones)."""
    path = vault / CONFIG
    if not path.is_file():
        return {}
    _, body = read_frontmatter(path)
    configs: dict[str, MapConfig] = {}
    current: MapConfig | None = None
    intro: list[str] = []
    for line in body.splitlines():
        if m := re.match(r"^##\s+([a-z0-9][a-z0-9_-]*)\s*$", line.strip(), re.I):
            if current is not None:
                current.intro = "\n".join(intro).strip()
            current, intro = configs.setdefault(m.group(1).lower(), MapConfig()), []
        elif current is None:
            continue
        elif m := re.match(r"^title:\s*(.+)$", line.strip()):
            current.title = m.group(1).strip()
        elif m := re.match(r"^[-*]\s+([^:]+):\s*(.*)$", line.strip()):
            name, values = m.group(1).strip(), m.group(2)
            if name.casefold() == "start here":
                current.start = [t.strip() for t in WIKILINK.findall(values)]
            else:
                current.sections.append((name, [v.strip().casefold() for v in values.split(",") if v.strip()]))
        else:
            intro.append(line)
    if current is not None:
        current.intro = "\n".join(intro).strip()
    return configs


def collect(vault: Path) -> list[Note]:
    notes = []
    for path in discover_notes(vault):
        fm, body = read_frontmatter(path)
        domains = sorted({m.group(1).lower() for t in _tags(fm) if (m := DOMAIN_TAG.match(t))})
        kind = fm.get("kind")
        notes.append(Note(
            rel=path.relative_to(vault).with_suffix("").as_posix(), name=path.stem,
            kind=str(kind).strip().casefold() if isinstance(kind, str) and kind.strip() else "",
            description=_one_line(fm.get("description")), domains=domains,
            when=_date(fm.get("processed_date")) or _date(fm.get("created")),
            links={t.strip() for t in WIKILINK.findall(body)},
        ))
    return notes


def resolve_links(notes: list[Note]) -> dict[str, set[str]]:
    """Each note's outgoing links as note paths; a link resolves by path, then by file name."""
    by_path = {n.rel.casefold(): n.rel for n in notes}
    by_name: dict[str, str] = {}
    for n in notes:
        by_name.setdefault(n.name.casefold(), n.rel)
    out: dict[str, set[str]] = {}
    for n in notes:
        targets = set()
        for raw in n.links:
            key = raw.removesuffix(".md").strip("/").casefold()
            target = by_path.get(key) or by_name.get(key.rsplit("/", 1)[-1])
            if target and target != n.rel:
                targets.add(target)
        out[n.rel] = targets
    return out


def _entry(n: Note) -> str:
    return f"- [[{n.rel}|{n.name}]]" + (f" — {n.description}" if n.description else "")


def _kind_heading(kind: str) -> str:
    return kind.replace("-", " ").capitalize() if kind else "Other notes"


def _node_id(*parts: str) -> str:
    return hashlib.sha1("\0".join(parts).encode()).hexdigest()[:16]


def group_notes(members: list[Note], cfg: MapConfig) -> list[tuple[str, list[Note]]]:
    """The config's sections in order, then the remaining kinds by size, notes without a kind last."""
    placed: dict[str, list[Note]] = defaultdict(list)
    rest: dict[str, list[Note]] = defaultdict(list)
    for n in members:
        section = next((name for name, kinds in cfg.sections if n.kind in kinds), None)
        (placed[section] if section else rest[n.kind]).append(n)
    groups = [(name, placed[name]) for name, _ in cfg.sections if placed[name]]
    kinds = sorted(rest, key=lambda k: (k == "", -len(rest[k]), k))
    return groups + [(_kind_heading(k), rest[k]) for k in kinds]


def build(vault: Path, today: date) -> tuple[dict[str, str], dict]:
    notes = collect(vault)
    links = resolve_links(notes)
    inbound = Counter(t for targets in links.values() for t in targets)
    by_rel = {n.rel: n for n in notes}
    configs = read_config(vault)
    members: dict[str, list[Note]] = defaultdict(list)
    for n in notes:
        for d in n.domains:
            members[d].append(n)
    domains = sorted(d for d in members if len(members[d]) >= MIN_NOTES or d in configs)
    new_since = (today - timedelta(days=NEW_DAYS)).isoformat()
    titles = {d: (configs.get(d) or MapConfig()).title or default_title(d) for d in domains}

    files: dict[str, str] = {}
    overview_rows = []
    for d in domains:
        cfg = configs.get(d) or MapConfig()
        group = sorted(members[d], key=lambda n: n.name.casefold())
        pinned = [by_rel[r] for r in (_resolve_one(t, by_rel) for t in cfg.start) if r and d in by_rel[r].domains]
        hubs = [n for n in sorted(group, key=lambda n: (-inbound[n.rel], n.name.casefold())) if inbound[n.rel] and n.rel not in {p.rel for p in pinned}]
        start = (pinned + hubs)[:START_HERE]
        new = sorted((n for n in group if n.when >= new_since), key=lambda n: (n.when, n.name.casefold()), reverse=True)
        cotags = Counter(o for n in group for o in n.domains if o != d and o in titles)
        newest = max(group, key=lambda n: (n.when, n.name.casefold()))

        out = ["---", f"generated_by: {GENERATOR}", f"domain: {d}", "cssclasses:", "  - map",
               "aliases:", f"  - {json.dumps(titles[d], ensure_ascii=False)}", "---",
               f"# {titles[d]}", "", HEADER, ""]
        if cfg.intro:
            out += [cfg.intro, ""]
        out += [f"*{len(group)} notes · [[{MAPS}/{d}.canvas|Canvas]] · [[{MAPS}/Overview|All maps]]*", ""]
        out += ["## Start here", ""] + ([_entry(n) for n in start] or ["- (no note in this domain is linked yet)"]) + [""]
        out += [f"## New (last {NEW_DAYS} days)", ""] + ([_entry(n) for n in new] or ["- (nothing new)"]) + [""]
        out += ["## All notes", ""]
        for heading, notes_in in group_notes(group, cfg):
            out += [f"### {heading}", ""] + [_entry(n) for n in notes_in] + [""]
        if cotags:
            out += ["## Neighbouring domains", ""]
            out += [f"- [[{MAPS}/{o}|{titles[o]}]] — {c} shared notes" for o, c in
                    sorted(cotags.items(), key=lambda kv: (-kv[1], kv[0]))[:NEIGHBOURS]] + [""]
        files[f"{MAPS}/{d}.md"] = "\n".join(out).rstrip() + "\n"
        files[f"{MAPS}/{d}.canvas"] = _domain_canvas(d, start, new, links)
        overview_rows.append((d, len(group), newest, cotags))

    files[f"{MAPS}/Overview.md"] = _overview_md(overview_rows, titles, len([n for n in notes if not n.domains]))
    files[f"{MAPS}/Overview.canvas"] = _overview_canvas(overview_rows)
    stats = {"notes": len(notes), "domains": len(domains), "untagged": sum(1 for n in notes if not n.domains),
             "maps": {d: len(members[d]) for d in domains}}
    return files, stats


def _resolve_one(target: str, by_rel: dict[str, Note]) -> str | None:
    key = target.removesuffix(".md").strip("/").casefold()
    for rel, n in by_rel.items():
        if rel.casefold() == key or n.name.casefold() == key.rsplit("/", 1)[-1]:
            return rel
    return None


def _canvas(nodes: list[dict], edges: list[dict]) -> str:
    return json.dumps({"nodes": nodes, "edges": edges}, indent="\t", ensure_ascii=False) + "\n"


def _domain_canvas(d: str, start: list[Note], new: list[Note], links: dict[str, set[str]]) -> str:
    shown = list({n.rel: n for n in start + new}.values())
    by_kind: dict[str, list[Note]] = defaultdict(list)
    for n in shown:
        by_kind[n.kind].append(n)
    nodes: list[dict] = [{"id": _node_id(d, "map"), "type": "file", "file": f"{MAPS}/{d}.md",
                          "x": -(4 * CARD_W // 2 + 2 * GAP), "y": 0, "width": 4 * CARD_W // 2, "height": 900}]
    y = 0
    for kind in sorted(by_kind, key=lambda k: (k == "", -len(by_kind[k]), k)):
        items = by_kind[kind]
        rows = (len(items) + COLS - 1) // COLS
        width, height = COLS * CARD_W + (COLS + 1) * GAP, rows * CARD_H + (rows + 1) * GAP + GAP
        nodes.append({"id": _node_id(d, "group", kind), "type": "group", "label": _kind_heading(kind),
                      "x": 0, "y": y, "width": width, "height": height})
        for i, n in enumerate(items):
            nodes.append({"id": _node_id(d, n.rel), "type": "file", "file": f"{n.rel}.md",
                          "x": GAP + (i % COLS) * (CARD_W + GAP), "y": y + 2 * GAP + (i // COLS) * (CARD_H + GAP),
                          "width": CARD_W, "height": CARD_H})
        y += height + GAP
    ids = {n.rel for n in shown}
    edges = [{"id": _node_id(d, a, b), "fromNode": _node_id(d, a), "fromSide": "right",
              "toNode": _node_id(d, b), "toSide": "left"}
             for a in sorted(ids) for b in sorted(links.get(a, set()) & ids)]
    return _canvas(nodes, edges)


def _overview_md(rows: list, titles: dict[str, str], untagged: int) -> str:
    out = ["---", f"generated_by: {GENERATOR}", "cssclasses:", "  - map", "---", "# Maps", "", HEADER, "",
           "One map per `domain/*` tag on at least three notes (or configured in `Config/toolkit/maps.md`). Each map lists every note in its domain; the canvas shows its hubs and newest notes.", "",
           "| Map | Notes | Newest | Neighbours |", "|---|---:|---|---|"]
    for d, count, newest, cotags in sorted(rows, key=lambda r: (-r[1], r[0])):
        near = ", ".join(f"[[{MAPS}/{o}\\|{titles[o]}]]" for o, _ in sorted(cotags.items(), key=lambda kv: (-kv[1], kv[0]))[:3])
        out.append(f"| [[{MAPS}/{d}\\|{titles[d]}]] ([[{MAPS}/{d}.canvas\\|canvas]]) | {count} | "
                   f"[[{newest.rel}\\|{newest.name}]] | {near} |")
    out += ["", f"{untagged} active notes carry no `domain/*` tag; `Index.md` lists them all.",
            "", f"[[{MAPS}/Overview.canvas|Overview canvas]] · [[Index]] · [[Now]]"]
    return "\n".join(out) + "\n"


def _overview_canvas(rows: list) -> str:
    cols, w, h = 4, 400, 260
    nodes, edges, seen = [], [], set()
    for i, (d, _count, _newest, _co) in enumerate(sorted(rows, key=lambda r: (-r[1], r[0]))):
        nodes.append({"id": _node_id("overview", d), "type": "file", "file": f"{MAPS}/{d}.md",
                      "x": (i % cols) * (w + 2 * GAP), "y": (i // cols) * (h + 2 * GAP), "width": w, "height": h})
    for d, _count, _newest, cotags in rows:
        for o, c in sorted(cotags.items(), key=lambda kv: (-kv[1], kv[0]))[:3]:
            pair = tuple(sorted((d, o)))
            if pair in seen:
                continue
            seen.add(pair)
            edges.append({"id": _node_id("overview", *pair), "fromNode": _node_id("overview", pair[0]),
                          "toNode": _node_id("overview", pair[1]), "label": str(c)})
    return _canvas(nodes, sorted(edges, key=lambda e: e["id"]))


def stale_files(vault: Path, keep: set[str]) -> list[Path]:
    """Maps this generator wrote for a domain that no longer has one."""
    stale = []
    for md in sorted((vault / MAPS).glob("*.md")):
        rel = md.relative_to(vault).as_posix()
        if rel in keep:
            continue
        fm, _ = read_frontmatter(md)
        if fm.get("generated_by") == GENERATOR:
            stale += [md] + [c for c in [md.with_suffix(".canvas")] if c.is_file()]
    return stale


def write(vault: Path, files: dict[str, str]) -> dict[str, list[str]]:
    changed, removed = [], []
    for rel, text in files.items():
        path = vault / rel
        if path.is_file() and path.read_text(encoding="utf-8") == text:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        atomic_write(path, text)
        changed.append(rel)
    for path in stale_files(vault, set(files)):
        path.unlink()
        removed.append(path.relative_to(vault).as_posix())
    return {"changed": changed, "removed": removed}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Build the domain maps under Maps/")
    ap.add_argument("--dry-run", action="store_true", help="report what would be written, write nothing")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--today", default=None, help="YYYY-MM-DD (default: today)")
    args = ap.parse_args(argv)
    vault = require_vault()
    files, stats = build(vault, date.fromisoformat(args.today) if args.today else date.today())
    if args.dry_run:
        stats["would_change"] = [r for r, t in files.items()
                                 if not (vault / r).is_file() or (vault / r).read_text(encoding="utf-8") != t]
        stats["would_remove"] = [p.relative_to(vault).as_posix() for p in stale_files(vault, set(files))]
    else:
        stats.update(write(vault, files))
    if args.json:
        print(json.dumps(stats, indent=2))
    else:
        verb = "would change" if args.dry_run else "changed"
        n = len(stats.get("would_change", stats.get("changed", [])))
        print(f"{stats['domains']} maps from {stats['notes']} notes ({stats['untagged']} untagged); {verb} {n} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
