#!/usr/bin/env python3
"""Build Now.md (the vault's homepage) and Boards/Pipeline.md — deterministic, no model call.

    uv run scripts/now_build.py [--dry-run] [--json] [--today YYYY-MM-DD]

Now.md says what is going on first, and the long lists last, in Markdown any agent can read:

    Status                     the last run (pipeline-state.json), stuck and inbox counts, and the
                               Signal Radar's new/hot/rising blips (00_Memory/radar/signal.json,
                               written by its own routine, so labelled with its own time)
    Links                      Maps, Index, Log, the Signal Radar note, today's daily note, and the
                               published Signal Radar and last-run report artifacts, each only if it exists
    Live views                 Recently changed and Recently distilled, embedded from Vault.base
    Stuck                      parked captures (pipeline-state.json) and open DLQ notes; only if any
    Inbox                      the backlog in 01_Capture/, next captures in queue order; only if any
    This week (folded)         New / Enriched: notes the `pipeline …` commits of the last 7 days added
                               or changed, newest first; an added note is new only when it has no
                               processed_date or a real, non-estimated one in the window (no git:
                               processed_date, else created, in it). Radar: this week's strong items
                               (00_Memory/radar/state.jsonl). Distilled per day: last 14 days.

Embedded views render in Obsidian only; a folded callout (`> [!tip]- …`) is a plain blockquote
elsewhere. Boards/Pipeline.md is the same state as a Kanban board; it is rebuilt every run, so
dragging a card changes nothing.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from collections import Counter
from datetime import UTC, date, datetime, timedelta
from pathlib import Path
from urllib.parse import quote

from map_build import _date, _when
from pipeline_run import STATE, _order
from vault_utils import (
    atomic_write,
    contained,
    discover_notes,
    format_ts,
    one_line,
    profile_value,
    read_frontmatter,
    read_jsonl,
    require_vault,
    resolve_title,
    root_active_notes,
    utc_timestamp,
)

NOW = "Now.md"
BOARD = "Boards/Pipeline.md"
BASE = "Vault.base"
LIVE_VIEWS = ("Recently changed", "Recently distilled")
SIGNAL = "00_Memory/radar/signal.json"
SIGNAL_NOTE = "00_Memory/radar/Signal-Radar.md"
SIGNAL_STAGES = ("new", "hot", "rising")
SIGNAL_SHOW = 5
GENERATOR = "now_build.py"
WEEK = 7
CHART_DAYS = 14
SHOW = 25
RADAR_SHOW = 15
NEXT_UP = 10
HEADER = "> Generated by `now_build.py` at the end of every pipeline run. Never edit it by hand."

# docs.yml's rsync excludes (00_Memory/, 01_Capture/; 00_Daily/, the daily notes, belongs with
# them): a wikilink to a note under any of them is a guaranteed dead link on the published docs
# site, since the folder never lands in quartz/content. [earned: 2026-09-28 repo audit —
# Now.md/Pipeline.md regenerated dead links into both every run]
DOCS_EXCLUDED = ("00_Memory/", "01_Capture/", "00_Daily/")


def _obsidian_uri(vault: Path, rel: str) -> str:
    return f"obsidian://open?vault={quote(vault.name)}&file={quote(rel)}"


def _link(vault: Path, rel: str, title: str | None = None) -> str:
    """A reference to a note for generated navigation. Normally a wikilink; for a note under a
    folder the docs site excludes (`DOCS_EXCLUDED`), plain text plus an `obsidian://` deep link
    instead — still one click to the note inside Obsidian, but never a wikilink the site publisher
    cannot resolve."""
    rel = rel.removesuffix(".md")
    title = title or resolve_title(vault, rel)
    if rel.startswith(DOCS_EXCLUDED):
        return f"{title} ([open]({_obsidian_uri(vault, rel)}))"
    return f"[[{rel}|{title}]]"


def _capped(lines: list[str], limit: int = SHOW) -> list[str]:
    return lines[:limit] + ([f"- … and {len(lines) - limit} more"] if len(lines) > limit else [])


def _newest_first(paths: list[str], dated: dict[str, str]) -> list[str]:
    return sorted(sorted(paths), key=lambda p: dated.get(p, ""), reverse=True)


def this_week(vault: Path, since: date) -> tuple[list[str], list[str], str]:
    """(new, enriched, source): note paths from the pipeline's commits since `since`."""
    folders = ("02_Projects", "03_Areas", "04_Resources")
    git = subprocess.run(["git", "-C", str(vault), "log", f"--since={since.isoformat()}", "--grep=^pipeline",
                          "--name-status", "--format=tformat:@@", "--", *folders, ":(glob)*.md"],
                         capture_output=True, text=True, check=False)
    if git.returncode == 0 and (vault / ".git").exists():
        # Of the root files a run commits (Index.md, Now.md, Log.md …) only a root `status: active`
        # note is content (contract/VAULT_SCHEMA.md).
        root_notes = {p.name for p in root_active_notes(vault)}
        new, changed = set(), set()
        for line in git.stdout.splitlines():
            status, _, path = line.partition("\t")
            if not path.endswith(".md") or not (vault / path).is_file():
                continue
            if "/" not in path and path not in root_notes:
                continue
            (new if status.startswith("A") else changed).add(path)
        # A commit adds a file the first time git sees it, not only when it is distilled: the run
        # that put the vault into git "added" 1,322 notes, backfilled legacy dates among them.
        # [earned: 2026-09-26, Now.md "New this week (1322)"]
        fresh = {}
        for p in new:
            fm = read_frontmatter(vault / p)[0]
            raw = fm.get("processed_date")
            if raw is None or str(raw).strip() == "":
                fresh[p] = ""  # never distilled (a root or project note): new, listed last
            elif fm.get("processed_date_estimated") is not True and (when := _date(raw)) >= since.isoformat():
                fresh[p] = when
        # Exclude only what "New this week" actually lists (`fresh`), not every path ever added
        # since `since` (`new`): a note the pipeline both wrote and later enriched in the same
        # week — an estimated or pre-window `processed_date` keeps it out of `fresh` — used to
        # vanish from both lists, since its own creation commit's "A" excluded it here too.
        # [earned: 2026-09-28 battle test — a same-week L2 enrichment of a note the pipeline had
        # itself distilled four days earlier never appeared in Now.md at all]
        return _newest_first(list(fresh), fresh), sorted(changed - set(fresh)), "git"
    dated = {}
    for p in discover_notes(vault):
        when = _when(read_frontmatter(p)[0])
        if when >= since.isoformat():
            dated[p.relative_to(vault).as_posix()] = when
    return _newest_first(list(dated), dated), [], "processed_date"


def radar(vault: Path, since: date) -> list[dict]:
    best: dict[str, dict] = {}
    for row in read_jsonl(vault / "00_Memory" / "radar" / "state.jsonl"):
        if not row.get("strong") or str(row.get("run", "")) < since.isoformat():
            continue
        row["score"] = max((row.get("p") or {}).get(t, 0) for t in row["strong"])
        key = row.get("canonical") or row.get("url")
        if key not in best or row["score"] > best[key]["score"]:
            best[key] = row
    return sorted(best.values(), key=lambda r: (-r["score"], str(r.get("title"))))


def stuck(vault: Path) -> tuple[list[str], list[str]]:
    state_path = vault / STATE
    try:
        parked = json.loads(state_path.read_text(encoding="utf-8")).get("parked", []) if state_path.is_file() else []
    except json.JSONDecodeError:
        parked = []
    dlq = []
    for p in contained(sorted((vault / "00_Memory" / "dlq").glob("*.md")), vault):
        fm, _ = read_frontmatter(p)
        if str(fm.get("status", "active")) == "active":
            dlq.append(p.relative_to(vault).as_posix())
    return [p for p in parked if (vault / p).is_file()], dlq


def inbox(vault: Path, parked: list[str]) -> list[str]:
    captures = [p for p in contained((vault / "01_Capture").glob("*.md"), vault) if p.is_file()]
    ordered = sorted(captures, key=_order)
    return [p.relative_to(vault).as_posix() for p in ordered if p.relative_to(vault).as_posix() not in parked]


def per_day(vault: Path, today: date) -> list[tuple[str, int]]:
    days = [(today - timedelta(days=i)).isoformat() for i in range(CHART_DAYS - 1, -1, -1)]
    counts = Counter()
    for p in discover_notes(vault):
        d = _date(read_frontmatter(p)[0].get("processed_date"))
        if d in days:
            counts[d] += 1
    return [(d, counts[d]) for d in days]


def _last_run(vault: Path) -> str:
    try:
        run = json.loads((vault / STATE).read_text(encoding="utf-8")).get("last_run") or {}
    except (OSError, json.JSONDecodeError):
        return "no run yet"
    if not run:
        return "no run yet"
    return (f"last run {str(run.get('at', ''))[:16].replace('T', ' ')} UTC: "
            f"{run.get('distilled', 0)} distilled, {run.get('dropped', 0)} dropped, {run.get('failed', 0)} failed")


def _radar_line(r: dict) -> str:
    title = one_line(r.get("title") or r.get("url"), 120).replace("[", "(").replace("]", ")")
    topics = ", ".join(r["strong"])
    return f"- [{title}]({r.get('url')}) — {topics}" + (" · in vault" if r.get("in_vault") else "")


def _signal_line(vault: Path, today: date) -> str | None:
    """The Signal Radar's early warnings: its strongest new, hot or rising blips. Its own routine
    writes signal.json on its own clock, so the line carries the file's time, never this run's.
    None when the file is missing or malformed — Now.md then just leaves the line out."""
    try:
        data = json.loads((vault / SIGNAL).read_text(encoding="utf-8"))
        at = datetime.strptime(data["generated"], "%Y-%m-%dT%H:%M:%SZ")
        blips = [b for b in data["blips"] if b["stage"] in SIGNAL_STAGES][:SIGNAL_SHOW]
        names = [f"{one_line(b['name'], 60).replace('[', '(').replace(']', ')')} ({b['stage']}, {int(b['strength'])})"
                 for b in blips]
    except (OSError, ValueError, TypeError, KeyError, AttributeError):
        return None
    when = at.strftime("%H:%M UTC" if at.date() == today else "%Y-%m-%d %H:%M UTC")
    return f"**Signal Radar** (as of {when}): " + (" · ".join(names) or "nothing new, hot or rising")


def _signal_artifact_url(vault: Path) -> str:
    """radar's `signal_artifact_url`, resolved as radar resolves it (env var, then its profile
    note), read here without importing the sibling plugin."""
    if (env := os.environ.get("TOOLKIT_RADAR_SIGNAL_ARTIFACT_URL")) is not None:
        return env
    profile = vault / "Config" / "toolkit" / "radar.md"
    return str(read_frontmatter(profile)[0].get("signal_artifact_url") or "") if profile.is_file() else ""


def _nav(vault: Path, today: date) -> list[str]:
    nav = ["[[Maps/Overview|Maps]]", "[[Boards/Pipeline|Pipeline board]]", "[[Index]]"]
    if (vault / "Log.md").is_file():
        # Log.md is created lazily by log_vault.py on the first logged action (contract's generated
        # navigation table); link it only once it exists, so a fresh vault never ships a dead
        # [[Log]] wikilink. [earned: 2026-09-28 repo audit]
        nav.append("[[Log]]")
    daily = f"00_Daily/{today.isoformat()}.md"
    for rel, title in ((daily, "Today"), (SIGNAL_NOTE, "Signal Radar")):
        if (vault / rel).is_file():
            nav.append(_link(vault, rel, title))
    for title, url in (("Signal Radar (claude.ai)", _signal_artifact_url(vault)),
                       ("Last run report (claude.ai)", str(profile_value(vault, "report_artifact_url") or ""))):
        if url:
            nav.append(f"[{title}]({url})")
    return nav


def _callout(kind: str, title: str, lines: list[str], folded: bool = False) -> list[str]:
    return [f"> [!{kind}]{'-' if folded else ''} {title}"] + [f"> {ln}" if ln else ">" for ln in lines] + [""]


def build(vault: Path, today: date) -> tuple[dict[str, str], dict]:
    since = today - timedelta(days=WEEK)
    new, enriched, source = this_week(vault, since)
    strong = radar(vault, since)
    parked, dlq = stuck(vault)
    queue = inbox(vault, parked)
    chart = per_day(vault, today)
    peak = max((c for _, c in chart), default=0) or 1

    held = len(parked) + len(dlq)
    waiting = (f"**{held} stuck**" if held else "Nothing stuck") + " · " + (
        f"**{len(queue)} waiting** in the inbox" if queue else "inbox empty")
    status = [f"*Generated {format_ts(utc_timestamp())} · {_last_run(vault)}*", "", waiting]
    if signal := _signal_line(vault, today):
        status += ["", signal]
    out = ["---", f"generated_by: {GENERATOR}", "cssclasses:", "  - dashboard", "---", "# Now", "", HEADER, "",
           *status, "", " · ".join(_nav(vault, today)), ""]
    for view in LIVE_VIEWS:
        out += [f"## {view}", "", f"![[{BASE}#{view}]]", ""]
    # Stuck and Inbox appear only when something waits; the callout says it in plain Markdown, the
    # embedded view (Obsidian only) keeps it live.
    if held:
        out += _callout("warning", f"Stuck ({held})",
                        [f"- parked: {_link(vault, p)}" for p in parked] + [f"- DLQ: {_link(vault, p)}" for p in dlq])
        out += [f"![[{BASE}#Stuck]]", ""]
    if queue:
        out += _callout("abstract", f"Inbox ({len(queue)} waiting)",
                        [f"- {_link(vault, p)}" for p in queue[:NEXT_UP]] + ([f"- … and {len(queue) - NEXT_UP} more"] if len(queue) > NEXT_UP else []),
                        folded=True)
        out += [f"![[{BASE}#Inbox]]", ""]
    out += [f"## This week (since {since.isoformat()})", ""]
    out += _callout("success", f"New this week ({len(new)})", _capped([f"- {_link(vault, p)}" for p in new]) or ["- (none)"],
                    folded=True)
    out += _callout("info", f"Enriched this week ({len(enriched)})",
                    _capped([f"- {_link(vault, p)}" for p in enriched]) or [f"- ({'none' if source == 'git' else 'needs git history'})"],
                    folded=True)
    out += _callout("tip", f"Radar: strong this week ({len(strong)})",
                    _capped([_radar_line(r) for r in strong], RADAR_SHOW) or ["- (none)"], folded=True)
    out += _callout("note", "Distilled per day", ["```text"] + [f"{d[5:]} {'█' * round(20 * c / peak):<20} {c}" for d, c in chart] + ["```"],
                    folded=True)
    now_md = "\n".join(out).rstrip() + "\n"

    lanes = {
        "Inbox": [f"- [ ] {_link(vault, p)}" for p in queue[:SHOW]],
        "Stuck": [f"- [ ] {_link(vault, p)}" for p in parked + dlq],
        "Radar this week": [f"- [ ] {_radar_line(r)[2:]}" for r in strong[:SHOW]],
        "New notes this week": [f"- [ ] {_link(vault, p)}" for p in new[:SHOW]],
    }
    board = ["---", "kanban-plugin: board", f"generated_by: {GENERATOR}",
             "note: Rebuilt every pipeline run from the vault's state; dragging a card changes nothing. Act in the notes.",
             "---", ""]
    for lane, items in lanes.items():
        board += [f"## {lane}", ""] + items + [""]
    board += ["%% kanban:settings", "```", json.dumps({"kanban-plugin": "board", "list-collapse": [False] * len(lanes)}), "```", "%%"]
    stats = {"new": len(new), "enriched": len(enriched), "source": source, "radar": len(strong),
             "parked": len(parked), "dlq": len(dlq), "inbox": len(queue)}
    return {NOW: now_md, BOARD: "\n".join(board) + "\n"}, stats


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Build Now.md and Boards/Pipeline.md")
    ap.add_argument("--dry-run", action="store_true", help="report what would be written, write nothing")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--today", default=None, help="YYYY-MM-DD (default: today, UTC)")
    args = ap.parse_args(argv)
    vault = require_vault()
    files, stats = build(vault, date.fromisoformat(args.today) if args.today else datetime.now(UTC).date())
    changed = [r for r, t in files.items() if not (vault / r).is_file() or (vault / r).read_text(encoding="utf-8") != t]
    if not args.dry_run:
        for rel in changed:
            (vault / rel).parent.mkdir(parents=True, exist_ok=True)
            atomic_write(vault / rel, files[rel])
    stats["would_change" if args.dry_run else "changed"] = changed
    print(json.dumps(stats, indent=2) if args.json else
          f"Now.md: {stats['new']} new, {stats['enriched']} enriched, {stats['radar']} radar, "
          f"{stats['parked'] + stats['dlq']} stuck, {stats['inbox']} in the inbox; "
          f"{'would change' if args.dry_run else 'changed'} {len(changed)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
