#!/usr/bin/env python3
"""Build Now.md (the vault's homepage) and Boards/Pipeline.md — deterministic, no model call.

    uv run scripts/now_build.py [--dry-run] [--json] [--today YYYY-MM-DD]

Now.md says what is going on first, and the long lists last, in Markdown any agent can read:

    Status                     health (`watchdog.health`: a word, the pipeline's and the radar's
                               last UTC times); the last run's receipt from the ledger's newest run
                               row (00_Memory/imports.jsonl: what came in, what it did, what it
                               dropped and why, from the retired rows it wrote), else
                               pipeline-state.json's last_run; stuck and inbox counts; the Signal
                               Radar's new/hot/rising blips (00_Memory/radar/signal.json, written by
                               its own routine, so labelled with its own time); new topics (concept
                               notes distilled this week) and the radar's strongest blind spots
    Links                      Maps, Index, Log, the Signal Radar note, today's daily note, and the
                               published Signal Radar and last-run report artifacts, each only if it exists
    Live views                 Recently changed and Recently distilled, embedded from Vault.base
    Stuck                      parked captures (pipeline-state.json) and open DLQ notes; only if any
    Inbox                      the backlog in 01_Capture/, next captures in queue order; only if any
    This week (folded)         New: notes distilled since the window opened (`distilled_when`, the
                               one rule of every per-day count: a distilled note's `distilled_at`,
                               else `processed_date`; never an estimated one). Enriched: notes whose
                               `updated_at` falls in the window and that are not new; the title says
                               so when the window opens before the vault's first `updated_at`. Both
                               newest first, from frontmatter alone: a count never depends on how
                               much git history a checkout has. Radar: this week's strong items
                               (00_Memory/radar/state.jsonl). Distilled per day: last 14 days, by
                               the same rule as New.

Every time on the page is absolute UTC, never "5 min ago": the page is read hours after it is built.

Embedded views render in Obsidian only; a folded callout (`> [!tip]- …`) is a plain blockquote
elsewhere. Boards/Pipeline.md is the same state as a Kanban board; it is rebuilt every run, so
dragging a card changes nothing.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter
from datetime import UTC, date, datetime, timedelta
from pathlib import Path
from urllib.parse import quote

import imports_log
from pipeline_run import STATE, _order
from vault_utils import (
    atomic_write,
    contained,
    discover_notes,
    distilled_when,
    format_ts,
    one_line,
    profile_value,
    read_frontmatter,
    read_jsonl,
    require_vault,
    resolve_title,
    utc_text,
    utc_timestamp,
)

NOW = "Now.md"
BOARD = "Boards/Pipeline.md"
BASE = "Vault.base"
LIVE_VIEWS = ("Recently changed", "Recently distilled")
SIGNAL = "00_Memory/radar/signal.json"
SIGNAL_NOTE = "00_Memory/radar/Signal-Radar.md"
SIGNAL_STAGES = ("new", "hot", "rising")
SIGNAL_SHOW = 5
BLIND_SHOW = 5
TOPICS_SHOW = 4
DROPS_SHOW = 3
CONCEPTS = "04_Resources/Concepts/"
HEALTH = {"healthy": "✅ healthy", "late": "⚠ late", "failing": "⛔ failing", "stuck": "⏸ stuck"}
GENERATOR = "now_build.py"
WEEK = 7
CHART_DAYS = 14
SHOW = 25
RADAR_SHOW = 15
NEXT_UP = 10
HEADER = "> Generated by `now_build.py` at the end of every pipeline run. Never edit it by hand."

# docs.yml's rsync excludes (00_Memory/, 01_Capture/; 00_Daily/, the daily notes, belongs with
# them): a wikilink to a note under any of them is a guaranteed dead link on the published docs
# site, since the folder never lands in quartz/content. [earned: 2026-09-28 repo audit —
# Now.md/Pipeline.md regenerated dead links into both every run]
DOCS_EXCLUDED = ("00_Memory/", "01_Capture/", "00_Daily/")


def _obsidian_uri(vault: Path, rel: str) -> str:
    return f"obsidian://open?vault={quote(vault.name)}&file={quote(rel)}"


def _link(vault: Path, rel: str, title: str | None = None) -> str:
    """A reference to a note for generated navigation. Normally a wikilink; for a note under a
    folder the docs site excludes (`DOCS_EXCLUDED`), plain text plus an `obsidian://` deep link
    instead — still one click to the note inside Obsidian, but never a wikilink the site publisher
    cannot resolve."""
    rel = rel.removesuffix(".md")
    title = title or resolve_title(vault, rel)
    if rel.startswith(DOCS_EXCLUDED):
        return f"{title} ([open]({_obsidian_uri(vault, rel)}))"
    return f"[[{rel}|{title}]]"


def _capped(lines: list[str], limit: int = SHOW) -> list[str]:
    return lines[:limit] + ([f"- … and {len(lines) - limit} more"] if len(lines) > limit else [])


def _newest_first(paths: list[str], dated: dict[str, str]) -> list[str]:
    return sorted(sorted(paths), key=lambda p: dated.get(p, ""), reverse=True)


def this_week(vault: Path, since: date) -> tuple[list[str], list[str], str]:
    """(new, enriched, source): content notes distilled since `since`, and the ones whose
    `updated_at` falls in the window without being new; each newest first, ties by path.

    Frontmatter alone, never git: the `pipeline …` commits this read before undercounted in a
    shallow clone, where Now.md said "52 new" for a week the full history put at 192 and the
    notes' own stamps at ~290. [earned: 2026-09-29, the cloud routine's Now.md]"""
    day = since.isoformat()
    new, enriched = {}, {}
    for p in discover_notes(vault):
        fm = read_frontmatter(p)[0]
        rel = p.relative_to(vault).as_posix()
        if (when := distilled_when(fm)) and when[:10] >= day:
            new[rel] = when
        elif (when := utc_text(fm.get("updated_at"))) and when[:10] >= day:
            enriched[rel] = when
    return _newest_first(list(new), new), _newest_first(list(enriched), enriched), "frontmatter"


def first_updated(vault: Path) -> str:
    """The UTC day of the earliest `updated_at` among the content notes, "" when none has one:
    before that day an enrichment left no stamp to count."""
    days = [when[:10] for p in discover_notes(vault) if (when := utc_text(read_frontmatter(p)[0].get("updated_at")))]
    return min(days, default="")


def radar(vault: Path, since: date) -> list[dict]:
    best: dict[str, dict] = {}
    for row in read_jsonl(vault / "00_Memory" / "radar" / "state.jsonl"):
        if not row.get("strong") or str(row.get("run", "")) < since.isoformat():
            continue
        row["score"] = max((row.get("p") or {}).get(t, 0) for t in row["strong"])
        key = row.get("canonical") or row.get("url")
        if key not in best or row["score"] > best[key]["score"]:
            best[key] = row
    return sorted(best.values(), key=lambda r: (-r["score"], str(r.get("title"))))


def stuck(vault: Path) -> tuple[list[str], list[str]]:
    state_path = vault / STATE
    try:
        parked = json.loads(state_path.read_text(encoding="utf-8")).get("parked", []) if state_path.is_file() else []
    except json.JSONDecodeError:
        parked = []
    dlq = []
    for p in contained(sorted((vault / "00_Memory" / "dlq").glob("*.md")), vault):
        fm, _ = read_frontmatter(p)
        if str(fm.get("status", "active")) == "active":
            dlq.append(p.relative_to(vault).as_posix())
    return [p for p in parked if (vault / p).is_file()], dlq


def inbox(vault: Path, parked: list[str]) -> list[str]:
    captures = [p for p in contained((vault / "01_Capture").glob("*.md"), vault) if p.is_file()]
    ordered = sorted(captures, key=_order)
    return [p.relative_to(vault).as_posix() for p in ordered if p.relative_to(vault).as_posix() not in parked]


def topics(vault: Path, new: list[str]) -> list[str]:
    """The new notes (`this_week`'s, so distilled by the same rule) that are concepts: under
    04_Resources/Concepts/ or `kind: concept`; in `new`'s order, newest first."""
    return [p for p in new if p.startswith(CONCEPTS) or read_frontmatter(vault / p)[0].get("kind") == "concept"]


def per_day(vault: Path, today: date) -> list[tuple[str, int]]:
    """Notes distilled on each of the last CHART_DAYS UTC days, by New's rule (`distilled_when`).
    [earned: 2026-09-29 audit — counting every `processed_date` put 92 on a day whose runs
    distilled 17: 75 `status: review` notes carry that date and were never distilled]"""
    days = [(today - timedelta(days=i)).isoformat() for i in range(CHART_DAYS - 1, -1, -1)]
    counts = Counter(distilled_when(read_frontmatter(p)[0])[:10] for p in discover_notes(vault))
    return [(d, counts[d]) for d in days]


def _at(stamp: object, today: date) -> str:
    """A stored UTC stamp (`YYYY-MM-DDTHH:MM:SSZ`) as `HH:MM UTC`, with its date when that is not
    `today`; "" when unreadable."""
    try:
        at = datetime.strptime(str(stamp), "%Y-%m-%dT%H:%M:%SZ")
    except ValueError:
        return ""
    return at.strftime("%H:%M UTC" if at.date() == today else "%Y-%m-%d %H:%M UTC")


def _plain(text: object, limit: int) -> str:
    """One line of someone else's text, its brackets made harmless for Markdown and wikilinks."""
    return one_line(str(text), limit).replace("[", "(").replace("]", ")")


def _health_line(vault: Path, today: date) -> str | None:
    """`watchdog.health` in one line: the word with its sign, the pipeline's and the radar's last
    times, and the detail when not healthy — but not `late`'s "last run N h ago", which a page read
    hours later turns into a lie (the pipeline's time says it). None when health cannot run:
    watchdog is imported here, not at the top, so a scripts folder without it still builds Now.md."""
    try:
        import watchdog
        h = watchdog.health(vault)
    except Exception:
        return None
    parts = [f"**{HEALTH.get(h['word'], h['word'])}**"]
    parts += [f"{name} {when}" for name, stamp in (("pipeline", h["pipeline_at"]), ("radar", h["radar_at"]))
              if (when := _at(stamp, today))]
    if not h["ok"] and (h["word"] != "late" or not h["pipeline_at"]):
        parts.append(str(h["detail"]))
    return " · ".join(parts)


def _receipt(vault: Path, today: date) -> list[str]:
    """The last run, from the ledger alone (never git): its run row's time, what came in (the
    summary's `in: …`, as `pipeline_run.came_in` writes it) and its counts; then what it dropped —
    the retired rows of kind dropped/duplicate written after the run before it (`end` writes the
    run row after the run retired its captures), each with its own reason, or with none. A newest
    run row without counts (written before 2026-09-29), or none: pipeline-state.json's line."""
    ran = imports_log.load(vault)
    if not ran or "distilled" not in ran[0]:
        return [_last_run(vault)]
    last, at = ran[0], str(ran[0].get("at") or "")
    before = str(ran[1].get("at") or f"{ran[1]['run'].replace(' ', 'T')}:00Z") if len(ran) > 1 else ""
    funnel = re.search(r"\bin: ([^;]*(?:; readwise [^;]*)?)", str(last.get("summary") or ""))
    line = (f"last run {_at(at, today) or last['run'] + ' UTC'}"
            + (f" · in: {funnel.group(1).replace('; ', ' · ')}" if funnel else "")
            + f" → {last['distilled']} distilled, {last.get('dropped', 0)} dropped, {last.get('failed', 0)} failed"
            + (" · history shallow" if last.get("shallow") else ""))
    titles = {it["capture"]: it["title"] for r in ran for it in r["items"] if it.get("capture") and it.get("title")}
    drops = [f"- dropped: {_plain(titles.get(r['retired']) or Path(str(r['retired'])).stem, 100)}"
             + (f" — {_plain(r['reason'], 160)}" if r.get("reason") else "")
             for r in read_jsonl(vault / imports_log.LOG)
             if r.get("retired") and r.get("kind") in ("dropped", "duplicate") and before < str(r.get("at") or "") <= at]
    return [line, *drops[:DROPS_SHOW]] + ([f"- … and {len(drops) - DROPS_SHOW} more"] if len(drops) > DROPS_SHOW else [])


def _last_run(vault: Path) -> str:
    try:
        run = json.loads((vault / STATE).read_text(encoding="utf-8")).get("last_run") or {}
    except (OSError, json.JSONDecodeError):
        return "no run yet"
    if not run:
        return "no run yet"
    return (f"last run {str(run.get('at', ''))[:16].replace('T', ' ')} UTC: "
            f"{run.get('distilled', 0)} distilled, {run.get('dropped', 0)} dropped, {run.get('failed', 0)} failed")


def _radar_line(r: dict) -> str:
    title = one_line(r.get("title") or r.get("url"), 120).replace("[", "(").replace("]", ")")
    topics = ", ".join(r["strong"])
    return f"- [{title}]({r.get('url')}) — {topics}" + (" · in vault" if r.get("in_vault") else "")


def _signal(vault: Path) -> dict | None:
    """signal.json, read once for both of its lines; None when missing or not JSON."""
    try:
        return json.loads((vault / SIGNAL).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def _signal_line(data: dict | None, today: date) -> str | None:
    """The Signal Radar's early warnings: its strongest new, hot or rising blips. Its own routine
    writes signal.json on its own clock, so the line carries the file's time, never this run's.
    None when the file is missing or malformed — Now.md then just leaves the line out."""
    try:
        when = _at(data["generated"], today)
        blips = [b for b in data["blips"] if b["stage"] in SIGNAL_STAGES][:SIGNAL_SHOW]
        names = [f"{_plain(b['name'], 60)} ({b['stage']}, {int(b['strength'])})" for b in blips]
    except (ValueError, TypeError, KeyError, AttributeError):
        return None
    return (f"**Signal Radar** (as of {when}): " + (" · ".join(names) or "nothing new, hot or rising")) if when else None


def _blind_line(data: dict | None) -> str | None:
    """The radar's blind spots — strong blips no vault note anchors (`blind_spots`, keys into
    `blips`) — the BLIND_SHOW strongest by name, and how many more. None when there are none or
    the file is missing or malformed."""
    try:
        by_key = {b["key"]: b for b in data["blips"]}
        spots = sorted((by_key[k] for k in data["blind_spots"]), key=lambda b: (-b["strength"], b["key"]))
        names = [_plain(b["name"], 60) for b in spots[:BLIND_SHOW]]
    except (TypeError, KeyError, AttributeError):
        return None
    more = f" (+{len(spots) - BLIND_SHOW} more, see the Signal Radar)" if len(spots) > BLIND_SHOW else ""
    return f"**Not in your vault yet:** {' · '.join(names)}{more}" if names else None


def _signal_artifact_url(vault: Path) -> str:
    """radar's `signal_artifact_url`, resolved as radar resolves it (env var, then its profile
    note), read here without importing the sibling plugin."""
    if (env := os.environ.get("TOOLKIT_RADAR_SIGNAL_ARTIFACT_URL")) is not None:
        return env
    profile = vault / "Config" / "toolkit" / "radar.md"
    return str(read_frontmatter(profile)[0].get("signal_artifact_url") or "") if profile.is_file() else ""


def _nav(vault: Path, today: date) -> list[str]:
    nav = ["[[Maps/Overview|Maps]]", "[[Boards/Pipeline|Pipeline board]]", "[[Index]]"]
    if (vault / "Log.md").is_file():
        # Log.md is created lazily by log_vault.py on the first logged action (contract's generated
        # navigation table); link it only once it exists, so a fresh vault never ships a dead
        # [[Log]] wikilink. [earned: 2026-09-28 repo audit]
        nav.append("[[Log]]")
    daily = f"00_Daily/{today.isoformat()}.md"
    for rel, title in ((daily, "Today"), (SIGNAL_NOTE, "Signal Radar")):
        if (vault / rel).is_file():
            nav.append(_link(vault, rel, title))
    for title, url in (("Signal Radar (claude.ai)", _signal_artifact_url(vault)),
                       ("Last run report (claude.ai)", str(profile_value(vault, "report_artifact_url") or "")),
                       ("Atlas (claude.ai)", str(profile_value(vault, "atlas_artifact_url") or ""))):
        if url:
            nav.append(f"[{title}]({url})")
    return nav


def _callout(kind: str, title: str, lines: list[str], folded: bool = False) -> list[str]:
    return [f"> [!{kind}]{'-' if folded else ''} {title}"] + [f"> {ln}" if ln else ">" for ln in lines] + [""]


def build(vault: Path, today: date) -> tuple[dict[str, str], dict]:
    since = today - timedelta(days=WEEK)
    new, enriched, source = this_week(vault, since)
    strong = radar(vault, since)
    parked, dlq = stuck(vault)
    queue = inbox(vault, parked)
    chart = per_day(vault, today)
    peak = max((c for _, c in chart), default=0) or 1
    fresh = topics(vault, new)
    signal = _signal(vault)

    held = len(parked) + len(dlq)
    waiting = (f"**{held} stuck**" if held else "Nothing stuck") + " · " + (
        f"**{len(queue)} waiting** in the inbox" if queue else "inbox empty")
    health = _health_line(vault, today)
    receipt, *drops = _receipt(vault, today)
    status = [*([health, ""] if health else []), f"*Generated {format_ts(utc_timestamp())} · {receipt}*", *drops, "", waiting]
    new_topics = ("**New topics:** " + " · ".join(_link(vault, p) for p in fresh[:TOPICS_SHOW])
                  + (f" … and {len(fresh) - TOPICS_SHOW} more" if len(fresh) > TOPICS_SHOW else "")) if fresh else None
    for line in (_signal_line(signal, today), new_topics, _blind_line(signal)):
        if line:
            status += ["", line]
    out = ["---", f"generated_by: {GENERATOR}", "cssclasses:", "  - dashboard", "---", "# Now", "", HEADER, "",
           *status, "", " · ".join(_nav(vault, today)), ""]
    for view in LIVE_VIEWS:
        out += [f"## {view}", "", f"![[{BASE}#{view}]]", ""]
    # Stuck and Inbox appear only when something waits; the callout says it in plain Markdown, the
    # embedded view (Obsidian only) keeps it live.
    if held:
        out += _callout("warning", f"Stuck ({held})",
                        [f"- parked: {_link(vault, p)}" for p in parked] + [f"- DLQ: {_link(vault, p)}" for p in dlq])
        out += [f"![[{BASE}#Stuck]]", ""]
    if queue:
        out += _callout("abstract", f"Inbox ({len(queue)} waiting)",
                        [f"- {_link(vault, p)}" for p in queue[:NEXT_UP]] + ([f"- … and {len(queue) - NEXT_UP} more"] if len(queue) > NEXT_UP else []),
                        folded=True)
        out += [f"![[{BASE}#Inbox]]", ""]
    out += [f"## This week (since {since.isoformat()})", ""]
    out += _callout("success", f"New this week ({len(new)} notes distilled)", _capped([f"- {_link(vault, p)}" for p in new]) or ["- (none)"],
                    folded=True)
    # `updated_at` is young: a window that opens before the first stamp undercounts, and the title
    # says so instead of passing the number off as the whole week.
    first = first_updated(vault)
    counted = ("; no note has updated_at yet" if not first else
               f"; counted since {first}, when updated_at started" if first > since.isoformat() else "")
    out += _callout("info", f"Enriched this week ({len(enriched)} notes changed{counted})",
                    _capped([f"- {_link(vault, p)}" for p in enriched]) or ["- (none)"], folded=True)
    out += _callout("tip", f"Radar: strong this week ({len(strong)})",
                    _capped([_radar_line(r) for r in strong], RADAR_SHOW) or ["- (none)"], folded=True)
    out += _callout("note", "Distilled per day (notes distilled)", ["```text"] + [f"{d[5:]} {'█' * round(20 * c / peak):<20} {c}" for d, c in chart] + ["```"],
                    folded=True)
    now_md = "\n".join(out).rstrip() + "\n"

    lanes = {
        "Inbox": [f"- [ ] {_link(vault, p)}" for p in queue[:SHOW]],
        "Stuck": [f"- [ ] {_link(vault, p)}" for p in parked + dlq],
        "Radar this week": [f"- [ ] {_radar_line(r)[2:]}" for r in strong[:SHOW]],
        "New notes this week": [f"- [ ] {_link(vault, p)}" for p in new[:SHOW]],
    }
    board = ["---", "kanban-plugin: board", f"generated_by: {GENERATOR}",
             "note: Rebuilt every pipeline run from the vault's state; dragging a card changes nothing. Act in the notes.",
             "---", ""]
    for lane, items in lanes.items():
        board += [f"## {lane}", ""] + items + [""]
    board += ["%% kanban:settings", "```", json.dumps({"kanban-plugin": "board", "list-collapse": [False] * len(lanes)}), "```", "%%"]
    stats = {"new": len(new), "enriched": len(enriched), "source": source, "radar": len(strong),
             "parked": len(parked), "dlq": len(dlq), "inbox": len(queue), "topics": len(fresh), "per_day": dict(chart)}
    return {NOW: now_md, BOARD: "\n".join(board) + "\n"}, stats


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Build Now.md and Boards/Pipeline.md")
    ap.add_argument("--dry-run", action="store_true", help="report what would be written, write nothing")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--today", default=None, help="YYYY-MM-DD (default: today, UTC)")
    args = ap.parse_args(argv)
    vault = require_vault()
    files, stats = build(vault, date.fromisoformat(args.today) if args.today else datetime.now(UTC).date())
    changed = [r for r, t in files.items() if not (vault / r).is_file() or (vault / r).read_text(encoding="utf-8") != t]
    if not args.dry_run:
        for rel in changed:
            (vault / rel).parent.mkdir(parents=True, exist_ok=True)
            atomic_write(vault / rel, files[rel])
    stats["would_change" if args.dry_run else "changed"] = changed
    print(json.dumps(stats, indent=2) if args.json else
          f"Now.md: {stats['new']} new, {stats['enriched']} enriched, {stats['radar']} radar, "
          f"{stats['parked'] + stats['dlq']} stuck, {stats['inbox']} in the inbox; "
          f"{'would change' if args.dry_run else 'changed'} {len(changed)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
