#!/usr/bin/env python3
"""Build Now.md (the vault's homepage) and Boards/Pipeline.md — deterministic, no model call.

    uv run scripts/now_build.py [--dry-run] [--json] [--today YYYY-MM-DD]

Now.md says what changed and what waits, in Markdown any agent can read:

    New / Enriched this week   notes the `pipeline …` commits of the last 7 days added or changed
                               (no git: notes whose processed_date is in the last 7 days are new)
    Radar                      this week's strong items (00_Memory/radar/state.jsonl)
    Stuck                      parked captures (pipeline-state.json) and open DLQ notes
    Inbox                      the backlog in 01_Capture/, next captures in queue order
    Distilled per day          notes by processed_date, last 14 days

Below it, for Obsidian only, live views embedded from Vault.base. Boards/Pipeline.md is the same
state as a Kanban board; it is rebuilt every run, so dragging a card changes nothing.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from collections import Counter
from datetime import date, timedelta
from pathlib import Path

from map_build import _date, _one_line
from pipeline_run import STATE, _order
from vault_utils import atomic_write, discover_notes, read_frontmatter, require_vault

NOW = "Now.md"
BOARD = "Boards/Pipeline.md"
BASE = "Vault.base"
BASE_VIEWS = ("Recently distilled", "Inbox", "Stuck")
GENERATOR = "now_build.py"
WEEK = 7
CHART_DAYS = 14
SHOW = 25
RADAR_SHOW = 15
NEXT_UP = 10
HEADER = "> Generated by `now_build.py` at the end of every pipeline run. Never edit it by hand."


def _link(rel: str) -> str:
    rel = rel.removesuffix(".md")
    return f"[[{rel}|{rel.rsplit('/', 1)[-1]}]]"


def _capped(lines: list[str], limit: int = SHOW) -> list[str]:
    return lines[:limit] + ([f"- … and {len(lines) - limit} more"] if len(lines) > limit else [])


def this_week(vault: Path, since: date) -> tuple[list[str], list[str], str]:
    """(new, enriched, source): note paths from the pipeline's commits since `since`."""
    folders = ("02_Projects", "03_Areas", "04_Resources")
    git = subprocess.run(["git", "-C", str(vault), "log", f"--since={since.isoformat()}", "--grep=^pipeline",
                          "--name-status", "--format=tformat:@@", "--", *folders],
                         capture_output=True, text=True, check=False)
    if git.returncode == 0 and (vault / ".git").exists():
        new, changed = set(), set()
        for line in git.stdout.splitlines():
            status, _, path = line.partition("\t")
            if not path.endswith(".md") or not (vault / path).is_file():
                continue
            (new if status.startswith("A") else changed).add(path)
        return sorted(new), sorted(changed - new), "git"
    new = []
    for p in discover_notes(vault):
        fm, _ = read_frontmatter(p)
        if _date(fm.get("processed_date")) >= since.isoformat():
            new.append(p.relative_to(vault).as_posix())
    return sorted(new), [], "processed_date"


def radar(vault: Path, since: date) -> list[dict]:
    path = vault / "00_Memory" / "radar" / "state.jsonl"
    if not path.is_file():
        return []
    best: dict[str, dict] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        try:
            row = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not row.get("strong") or str(row.get("run", "")) < since.isoformat():
            continue
        row["score"] = max((row.get("p") or {}).get(t, 0) for t in row["strong"])
        key = row.get("canonical") or row.get("url")
        if key not in best or row["score"] > best[key]["score"]:
            best[key] = row
    return sorted(best.values(), key=lambda r: (-r["score"], str(r.get("title"))))


def stuck(vault: Path) -> tuple[list[str], list[str]]:
    state_path = vault / STATE
    try:
        parked = json.loads(state_path.read_text(encoding="utf-8")).get("parked", []) if state_path.is_file() else []
    except json.JSONDecodeError:
        parked = []
    dlq = []
    for p in sorted((vault / "00_Memory" / "dlq").glob("*.md")):
        fm, _ = read_frontmatter(p)
        if str(fm.get("status", "active")) == "active":
            dlq.append(p.relative_to(vault).as_posix())
    return [p for p in parked if (vault / p).is_file()], dlq


def inbox(vault: Path, parked: list[str]) -> list[str]:
    captures = [p for p in (vault / "01_Capture").glob("*.md") if p.is_file()]
    ordered = sorted(captures, key=lambda p: _order(vault, p))
    return [p.relative_to(vault).as_posix() for p in ordered if p.relative_to(vault).as_posix() not in parked]


def per_day(vault: Path, today: date) -> list[tuple[str, int]]:
    days = [(today - timedelta(days=i)).isoformat() for i in range(CHART_DAYS - 1, -1, -1)]
    counts = Counter()
    for p in discover_notes(vault):
        d = _date(read_frontmatter(p)[0].get("processed_date"))
        if d in days:
            counts[d] += 1
    return [(d, counts[d]) for d in days]


def _last_run(vault: Path) -> str:
    try:
        run = json.loads((vault / STATE).read_text(encoding="utf-8")).get("last_run") or {}
    except (OSError, json.JSONDecodeError):
        return "no run yet"
    if not run:
        return "no run yet"
    return (f"last run {str(run.get('at', ''))[:16].replace('T', ' ')} UTC: "
            f"{run.get('distilled', 0)} distilled, {run.get('dropped', 0)} dropped, {run.get('failed', 0)} failed")


def _radar_line(r: dict) -> str:
    title = _one_line(r.get("title") or r.get("url"), 120).replace("[", "(").replace("]", ")")
    topics = ", ".join(r["strong"])
    return f"- [{title}]({r.get('url')}) — {topics}" + (" · in vault" if r.get("in_vault") else "")


def _callout(kind: str, title: str, lines: list[str]) -> list[str]:
    return [f"> [!{kind}] {title}"] + [f"> {ln}" if ln else ">" for ln in lines] + [""]


def build(vault: Path, today: date) -> tuple[dict[str, str], dict]:
    since = today - timedelta(days=WEEK)
    new, enriched, source = this_week(vault, since)
    strong = radar(vault, since)
    parked, dlq = stuck(vault)
    queue = inbox(vault, parked)
    chart = per_day(vault, today)
    peak = max((c for _, c in chart), default=0) or 1

    out = ["---", f"generated_by: {GENERATOR}", "cssclasses:", "  - dashboard", "---", "# Now", "", HEADER, "",
           f"*Week since {since.isoformat()} · {_last_run(vault)}*", "",
           "[[Maps/Overview|Maps]] · [[Boards/Pipeline|Pipeline board]] · [[Index]] · [[Log]]", ""]
    out += _callout("success", f"New this week ({len(new)})", _capped([f"- {_link(p)}" for p in new]) or ["- (none)"])
    out += _callout("info", f"Enriched this week ({len(enriched)})",
                    _capped([f"- {_link(p)}" for p in enriched]) or [f"- ({'none' if source == 'git' else 'needs git history'})"])
    out += _callout("tip", f"Radar: strong this week ({len(strong)})",
                    _capped([_radar_line(r) for r in strong], RADAR_SHOW) or ["- (none)"])
    out += _callout("warning", f"Stuck ({len(parked) + len(dlq)})",
                    [f"- parked: {_link(p)}" for p in parked] + [f"- DLQ: {_link(p)}" for p in dlq] or ["- (nothing stuck)"])
    out += _callout("abstract", f"Inbox ({len(queue)} waiting)",
                    [f"- {_link(p)}" for p in queue[:NEXT_UP]] + ([f"- … and {len(queue) - NEXT_UP} more"] if len(queue) > NEXT_UP else [])
                    or ["- (empty)"])
    out += _callout("note", "Distilled per day", ["```text"] + [f"{d[5:]} {'█' * round(20 * c / peak):<20} {c}" for d, c in chart] + ["```"])
    out += ["## Live views", "", "*Obsidian only; the sections above say the same in plain Markdown.*", ""]
    for view in BASE_VIEWS:
        out += [f"### {view}", "", f"![[{BASE}#{view}]]", ""]
    now_md = "\n".join(out).rstrip() + "\n"

    lanes = {
        "Inbox": [f"- [ ] {_link(p)}" for p in queue[:SHOW]],
        "Stuck": [f"- [ ] {_link(p)}" for p in parked + dlq],
        "Radar this week": [f"- [ ] {_radar_line(r)[2:]}" for r in strong[:SHOW]],
        "New notes this week": [f"- [ ] {_link(p)}" for p in new[:SHOW]],
    }
    board = ["---", "kanban-plugin: board", f"generated_by: {GENERATOR}",
             "note: Rebuilt every pipeline run from the vault's state; dragging a card changes nothing. Act in the notes.",
             "---", ""]
    for lane, items in lanes.items():
        board += [f"## {lane}", ""] + items + [""]
    board += ["%% kanban:settings", "```", json.dumps({"kanban-plugin": "board", "list-collapse": [False] * len(lanes)}), "```", "%%"]
    stats = {"new": len(new), "enriched": len(enriched), "source": source, "radar": len(strong),
             "parked": len(parked), "dlq": len(dlq), "inbox": len(queue)}
    return {NOW: now_md, BOARD: "\n".join(board) + "\n"}, stats


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Build Now.md and Boards/Pipeline.md")
    ap.add_argument("--dry-run", action="store_true", help="report what would be written, write nothing")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--today", default=None, help="YYYY-MM-DD (default: today)")
    args = ap.parse_args(argv)
    vault = require_vault()
    files, stats = build(vault, date.fromisoformat(args.today) if args.today else date.today())
    changed = [r for r, t in files.items() if not (vault / r).is_file() or (vault / r).read_text(encoding="utf-8") != t]
    if not args.dry_run:
        for rel in changed:
            (vault / rel).parent.mkdir(parents=True, exist_ok=True)
            atomic_write(vault / rel, files[rel])
    stats["would_change" if args.dry_run else "changed"] = changed
    print(json.dumps(stats, indent=2) if args.json else
          f"Now.md: {stats['new']} new, {stats['enriched']} enriched, {stats['radar']} radar, "
          f"{stats['parked'] + stats['dlq']} stuck, {stats['inbox']} in the inbox; "
          f"{'would change' if args.dry_run else 'changed'} {len(changed)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
